//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.11.90;Initial Catalog=Desktop_Local_v1931;Persist Security In" +
            "fo=True;User ID=cdoadmin")]
        public string Desktop_Local_v1931 {
            get {
                return ((string)(this["Desktop_Local_v1931"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.11.90;Initial Catalog=Desktop_Local_v1841;Persist Security In" +
            "fo=True;User ID=cdoadmin")]
        public string Desktop_Local_v1841 {
            get {
                return ((string)(this["Desktop_Local_v1841"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.11.90;Initial Catalog=Desktop_Local_v1851;Persist Security In" +
            "fo=True;User ID=cdoadmin;Password=cdoadmin")]
        public string Desktop_Local_v1851ConnectionString {
            get {
                return ((string)(this["Desktop_Local_v1851ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.11.83;Initial Catalog=Desktop_Local_v4051;User ID=cdoadmin")]
        public string Desktop_Local_v4051ConnectionString {
            get {
                return ((string)(this["Desktop_Local_v4051ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.11.90;Initial Catalog=Desktop_Local_v1811;Persist Security In" +
            "fo=True;User ID=cdoadmin")]
        public string v1811 {
            get {
                return ((string)(this["v1811"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DMLAPTOP\\SQLEXPRESS2008;Initial Catalog=DesktopData;Persist Security " +
            "Info=True;User ID=cdoadmin")]
        public string CWTDesktopDatabase {
            get {
                return ((string)(this["CWTDesktopDatabase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.11.48;Initial Catalog=Desktop_Local_v3041;User ID=cdoadmin")]
        public string Desktop_Local_v3041ConnectionString {
            get {
                return ((string)(this["Desktop_Local_v3041ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DMLAPTOP\\sqlexpress2008;Initial Catalog=Desktop_Local_v2011;Integrate" +
            "d Security=True")]
        public string Desktop_Local_v2011ConnectionString {
            get {
                return ((string)(this["Desktop_Local_v2011ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.49;Initial Catalog=Desktop_Local_v2091;User ID=cdoadmin")]
        public string v2091 {
            get {
                return ((string)(this["v2091"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.11.83;Initial Catalog=Desktop_Local_v4021;User ID=cdoadmin")]
        public string Desktop_Local_v4021ConnectionString1 {
            get {
                return ((string)(this["Desktop_Local_v4021ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.11.90;Initial Catalog=Desktop_Local_v1901;Persist Security In" +
            "fo=True;User ID=cdoadmin;Password=cdoadmin")]
        public string Desktop_Local_v1901ConnectionString {
            get {
                return ((string)(this["Desktop_Local_v1901ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DMLAPTOP2\\SQL2008;Initial Catalog=Desktop_Local_v2031;User ID=cdoadmi" +
            "n")]
        public string Desktop_Local_v2031 {
            get {
                return ((string)(this["Desktop_Local_v2031"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.11.90;Initial Catalog=Desktop_Local_v1911;Persist Security In" +
            "fo=True;User ID=cdoadmin")]
        public string Desktop_Local_v1911ConnectionString {
            get {
                return ((string)(this["Desktop_Local_v1911ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.11.90;Initial Catalog=Desktop_Local_v1921;Persist Security In" +
            "fo=True;User ID=cdoadmin;Password=cdoadmin")]
        public string Desktop_Local_v1921ConnectionString {
            get {
                return ((string)(this["Desktop_Local_v1921ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.11.90;Initial Catalog=Desktop_Local_v1931;Persist Security In" +
            "fo=True;User ID=cdoadmin;Password=cdoadmin")]
        public string Desktop_Local_v1931ConnectionString {
            get {
                return ((string)(this["Desktop_Local_v1931ConnectionString"]));
            }
        }
    }
}
