#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Desktop_Local_v1841")]
	public partial class PointOfSaleFeeLoadDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFeeLoadDescriptionType(FeeLoadDescriptionType instance);
    partial void UpdateFeeLoadDescriptionType(FeeLoadDescriptionType instance);
    partial void DeleteFeeLoadDescriptionType(FeeLoadDescriptionType instance);
    partial void InsertPointOfSaleFeeLoad(PointOfSaleFeeLoad instance);
    partial void UpdatePointOfSaleFeeLoad(PointOfSaleFeeLoad instance);
    partial void DeletePointOfSaleFeeLoad(PointOfSaleFeeLoad instance);
    #endregion
		
		public PointOfSaleFeeLoadDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Desktop_Local_v1841"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PointOfSaleFeeLoadDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PointOfSaleFeeLoadDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PointOfSaleFeeLoadDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PointOfSaleFeeLoadDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FeeLoadDescriptionType> FeeLoadDescriptionTypes
		{
			get
			{
				return this.GetTable<FeeLoadDescriptionType>();
			}
		}
		
		public System.Data.Linq.Table<PointOfSaleFeeLoad> PointOfSaleFeeLoads
		{
			get
			{
				return this.GetTable<PointOfSaleFeeLoad>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_DeletePointOfSaleFeeLoad_v1")]
		public int spDesktopDataAdmin_DeletePointOfSaleFeeLoad_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PointOfSaleFeeLoadId", DbType="Int")] System.Nullable<int> pointOfSaleFeeLoadId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientTopUnitGuid", DbType="VarChar(13)")] string clientTopUnitGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientSubUnitGuid", DbType="VarChar(13)")] string clientSubUnitGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelerTypeGuid", DbType="VarChar(13)")] string travelerTypeGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeeLoadDescriptionTypeCode", DbType="NVarChar(50)")] string feeLoadDescriptionTypeCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AgentInitiatedFlag", DbType="Bit")] System.Nullable<bool> agentInitiatedFlag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelIndicator", DbType="VarChar(1)")] string travelIndicator, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pointOfSaleFeeLoadId, clientTopUnitGuid, clientSubUnitGuid, travelerTypeGuid, feeLoadDescriptionTypeCode, productId, agentInitiatedFlag, travelIndicator, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_InsertPointOfSaleFeeLoad_v1")]
		public int spDesktopDataAdmin_InsertPointOfSaleFeeLoad_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientTopUnitGuid", DbType="VarChar(13)")] string clientTopUnitGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientSubUnitGuid", DbType="VarChar(13)")] string clientSubUnitGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelerTypeGuid", DbType="VarChar(13)")] string travelerTypeGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeeLoadDescriptionTypeCode", DbType="NVarChar(50)")] string feeLoadDescriptionTypeCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AgentInitiatedFlag", DbType="Bit")] System.Nullable<bool> agentInitiatedFlag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelIndicator", DbType="VarChar(1)")] string travelIndicator, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeeLoadAmount", DbType="Decimal(12,4)")] System.Nullable<decimal> feeLoadAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeeLoadCurrencyCode", DbType="NVarChar(5)")] string feeLoadCurrencyCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientTopUnitGuid, clientSubUnitGuid, travelerTypeGuid, feeLoadDescriptionTypeCode, productId, agentInitiatedFlag, travelIndicator, feeLoadAmount, feeLoadCurrencyCode, adminUserGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPointOfSaleFeeLoads_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPointOfSaleFeeLoads_v1Result> spDesktopDataAdmin_SelectPointOfSaleFeeLoads_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientTopUnitGuid", DbType="NVarChar(50)")] string clientTopUnitGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientSubUnitGuid", DbType="NVarChar(50)")] string clientSubUnitGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelerTypeGuid", DbType="VarChar(50)")] string travelerTypeGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortField", DbType="VarChar(50)")] string sortField, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientTopUnitGuid, clientSubUnitGuid, travelerTypeGuid, sortField, sortOrder, pageNumber, adminUserGuid);
			return ((ISingleResult<spDesktopDataAdmin_SelectPointOfSaleFeeLoads_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_UpdatePointOfSaleFeeLoad_v1")]
		public int spDesktopDataAdmin_UpdatePointOfSaleFeeLoad_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PointOfSaleFeeLoadId", DbType="Int")] System.Nullable<int> pointOfSaleFeeLoadId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientTopUnitGuid", DbType="VarChar(13)")] string clientTopUnitGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientSubUnitGuid", DbType="VarChar(13)")] string clientSubUnitGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelerTypeGuid", DbType="VarChar(13)")] string travelerTypeGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeeLoadDescriptionTypeCode", DbType="NVarChar(50)")] string feeLoadDescriptionTypeCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AgentInitiatedFlag", DbType="Bit")] System.Nullable<bool> agentInitiatedFlag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelIndicator", DbType="VarChar(1)")] string travelIndicator, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeeLoadAmount", DbType="Decimal(12,4)")] System.Nullable<decimal> feeLoadAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeeLoadCurrencyCode", DbType="NVarChar(5)")] string feeLoadCurrencyCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pointOfSaleFeeLoadId, clientTopUnitGuid, clientSubUnitGuid, travelerTypeGuid, feeLoadDescriptionTypeCode, productId, agentInitiatedFlag, travelIndicator, feeLoadAmount, feeLoadCurrencyCode, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FeeLoadDescriptionType")]
	public partial class FeeLoadDescriptionType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _FeeLoadDescriptionTypeCode;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private int _VersionNumber;
		
		private EntitySet<PointOfSaleFeeLoad> _PointOfSaleFeeLoads;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFeeLoadDescriptionTypeCodeChanging(string value);
    partial void OnFeeLoadDescriptionTypeCodeChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(int value);
    partial void OnVersionNumberChanged();
    #endregion
		
		public FeeLoadDescriptionType()
		{
			this._PointOfSaleFeeLoads = new EntitySet<PointOfSaleFeeLoad>(new Action<PointOfSaleFeeLoad>(this.attach_PointOfSaleFeeLoads), new Action<PointOfSaleFeeLoad>(this.detach_PointOfSaleFeeLoads));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeLoadDescriptionTypeCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string FeeLoadDescriptionTypeCode
		{
			get
			{
				return this._FeeLoadDescriptionTypeCode;
			}
			set
			{
				if ((this._FeeLoadDescriptionTypeCode != value))
				{
					this.OnFeeLoadDescriptionTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._FeeLoadDescriptionTypeCode = value;
					this.SendPropertyChanged("FeeLoadDescriptionTypeCode");
					this.OnFeeLoadDescriptionTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int NOT NULL")]
		public int VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FeeLoadDescriptionType_PointOfSaleFeeLoad", Storage="_PointOfSaleFeeLoads", ThisKey="FeeLoadDescriptionTypeCode", OtherKey="FeeLoadDescriptionTypeCode")]
		public EntitySet<PointOfSaleFeeLoad> PointOfSaleFeeLoads
		{
			get
			{
				return this._PointOfSaleFeeLoads;
			}
			set
			{
				this._PointOfSaleFeeLoads.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PointOfSaleFeeLoads(PointOfSaleFeeLoad entity)
		{
			this.SendPropertyChanging();
			entity.FeeLoadDescriptionType = this;
		}
		
		private void detach_PointOfSaleFeeLoads(PointOfSaleFeeLoad entity)
		{
			this.SendPropertyChanging();
			entity.FeeLoadDescriptionType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PointOfSaleFeeLoad")]
	public partial class PointOfSaleFeeLoad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PointOfSaleFeeLoadId;
		
		private string _ClientTopUnitGuid;
		
		private string _ClientSubUnitGuid;
		
		private string _TravelerTypeGuid;
		
		private string _FeeLoadDescriptionTypeCode;
		
		private int _ProductId;
		
		private bool _AgentInitiatedFlag;
		
		private string _TravelIndicator;
		
		private decimal _FeeLoadAmount;
		
		private string _FeeLoadCurrencyCode;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private int _VersionNumber;
		
		private EntityRef<FeeLoadDescriptionType> _FeeLoadDescriptionType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPointOfSaleFeeLoadIdChanging(int value);
    partial void OnPointOfSaleFeeLoadIdChanged();
    partial void OnClientTopUnitGuidChanging(string value);
    partial void OnClientTopUnitGuidChanged();
    partial void OnClientSubUnitGuidChanging(string value);
    partial void OnClientSubUnitGuidChanged();
    partial void OnTravelerTypeGuidChanging(string value);
    partial void OnTravelerTypeGuidChanged();
    partial void OnFeeLoadDescriptionTypeCodeChanging(string value);
    partial void OnFeeLoadDescriptionTypeCodeChanged();
    partial void OnProductIdChanging(int value);
    partial void OnProductIdChanged();
    partial void OnAgentInitiatedFlagChanging(bool value);
    partial void OnAgentInitiatedFlagChanged();
    partial void OnTravelIndicatorChanging(string value);
    partial void OnTravelIndicatorChanged();
    partial void OnFeeLoadAmountChanging(decimal value);
    partial void OnFeeLoadAmountChanged();
    partial void OnFeeLoadCurrencyCodeChanging(string value);
    partial void OnFeeLoadCurrencyCodeChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(int value);
    partial void OnVersionNumberChanged();
    #endregion
		
		public PointOfSaleFeeLoad()
		{
			this._FeeLoadDescriptionType = default(EntityRef<FeeLoadDescriptionType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointOfSaleFeeLoadId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PointOfSaleFeeLoadId
		{
			get
			{
				return this._PointOfSaleFeeLoadId;
			}
			set
			{
				if ((this._PointOfSaleFeeLoadId != value))
				{
					this.OnPointOfSaleFeeLoadIdChanging(value);
					this.SendPropertyChanging();
					this._PointOfSaleFeeLoadId = value;
					this.SendPropertyChanged("PointOfSaleFeeLoadId");
					this.OnPointOfSaleFeeLoadIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientTopUnitGuid", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string ClientTopUnitGuid
		{
			get
			{
				return this._ClientTopUnitGuid;
			}
			set
			{
				if ((this._ClientTopUnitGuid != value))
				{
					this.OnClientTopUnitGuidChanging(value);
					this.SendPropertyChanging();
					this._ClientTopUnitGuid = value;
					this.SendPropertyChanged("ClientTopUnitGuid");
					this.OnClientTopUnitGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientSubUnitGuid", DbType="VarChar(13)")]
		public string ClientSubUnitGuid
		{
			get
			{
				return this._ClientSubUnitGuid;
			}
			set
			{
				if ((this._ClientSubUnitGuid != value))
				{
					this.OnClientSubUnitGuidChanging(value);
					this.SendPropertyChanging();
					this._ClientSubUnitGuid = value;
					this.SendPropertyChanged("ClientSubUnitGuid");
					this.OnClientSubUnitGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelerTypeGuid", DbType="VarChar(13)")]
		public string TravelerTypeGuid
		{
			get
			{
				return this._TravelerTypeGuid;
			}
			set
			{
				if ((this._TravelerTypeGuid != value))
				{
					this.OnTravelerTypeGuidChanging(value);
					this.SendPropertyChanging();
					this._TravelerTypeGuid = value;
					this.SendPropertyChanged("TravelerTypeGuid");
					this.OnTravelerTypeGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeLoadDescriptionTypeCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FeeLoadDescriptionTypeCode
		{
			get
			{
				return this._FeeLoadDescriptionTypeCode;
			}
			set
			{
				if ((this._FeeLoadDescriptionTypeCode != value))
				{
					if (this._FeeLoadDescriptionType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFeeLoadDescriptionTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._FeeLoadDescriptionTypeCode = value;
					this.SendPropertyChanged("FeeLoadDescriptionTypeCode");
					this.OnFeeLoadDescriptionTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int NOT NULL")]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentInitiatedFlag", DbType="Bit NOT NULL")]
		public bool AgentInitiatedFlag
		{
			get
			{
				return this._AgentInitiatedFlag;
			}
			set
			{
				if ((this._AgentInitiatedFlag != value))
				{
					this.OnAgentInitiatedFlagChanging(value);
					this.SendPropertyChanging();
					this._AgentInitiatedFlag = value;
					this.SendPropertyChanged("AgentInitiatedFlag");
					this.OnAgentInitiatedFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelIndicator", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string TravelIndicator
		{
			get
			{
				return this._TravelIndicator;
			}
			set
			{
				if ((this._TravelIndicator != value))
				{
					this.OnTravelIndicatorChanging(value);
					this.SendPropertyChanging();
					this._TravelIndicator = value;
					this.SendPropertyChanged("TravelIndicator");
					this.OnTravelIndicatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeLoadAmount", DbType="Decimal(12,4) NOT NULL")]
		public decimal FeeLoadAmount
		{
			get
			{
				return this._FeeLoadAmount;
			}
			set
			{
				if ((this._FeeLoadAmount != value))
				{
					this.OnFeeLoadAmountChanging(value);
					this.SendPropertyChanging();
					this._FeeLoadAmount = value;
					this.SendPropertyChanged("FeeLoadAmount");
					this.OnFeeLoadAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeLoadCurrencyCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string FeeLoadCurrencyCode
		{
			get
			{
				return this._FeeLoadCurrencyCode;
			}
			set
			{
				if ((this._FeeLoadCurrencyCode != value))
				{
					this.OnFeeLoadCurrencyCodeChanging(value);
					this.SendPropertyChanging();
					this._FeeLoadCurrencyCode = value;
					this.SendPropertyChanged("FeeLoadCurrencyCode");
					this.OnFeeLoadCurrencyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int NOT NULL")]
		public int VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FeeLoadDescriptionType_PointOfSaleFeeLoad", Storage="_FeeLoadDescriptionType", ThisKey="FeeLoadDescriptionTypeCode", OtherKey="FeeLoadDescriptionTypeCode", IsForeignKey=true)]
		public FeeLoadDescriptionType FeeLoadDescriptionType
		{
			get
			{
				return this._FeeLoadDescriptionType.Entity;
			}
			set
			{
				FeeLoadDescriptionType previousValue = this._FeeLoadDescriptionType.Entity;
				if (((previousValue != value) 
							|| (this._FeeLoadDescriptionType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FeeLoadDescriptionType.Entity = null;
						previousValue.PointOfSaleFeeLoads.Remove(this);
					}
					this._FeeLoadDescriptionType.Entity = value;
					if ((value != null))
					{
						value.PointOfSaleFeeLoads.Add(this);
						this._FeeLoadDescriptionTypeCode = value.FeeLoadDescriptionTypeCode;
					}
					else
					{
						this._FeeLoadDescriptionTypeCode = default(string);
					}
					this.SendPropertyChanged("FeeLoadDescriptionType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPointOfSaleFeeLoads_v1Result
	{
		
		private int _PointOfSaleFeeLoadId;
		
		private string _ClientTopUnitGuid;
		
		private string _ClientTopUnitName;
		
		private string _ClientSubUnitGuid;
		
		private string _ClientSubUnitName;
		
		private string _TravelerTypeGuid;
		
		private string _TravelerTypeName;
		
		private string _FeeLoadDescriptionTypeCode;
		
		private int _ProductId;
		
		private string _ProductName;
		
		private bool _AgentInitiatedFlag;
		
		private string _TravelIndicator;
		
		private decimal _FeeLoadAmount;
		
		private string _FeeLoadCurrencyCode;
		
		private System.Nullable<bool> _HasWriteAccess;
		
		private System.Nullable<int> _RecordCount;
		
		public spDesktopDataAdmin_SelectPointOfSaleFeeLoads_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointOfSaleFeeLoadId", DbType="Int NOT NULL")]
		public int PointOfSaleFeeLoadId
		{
			get
			{
				return this._PointOfSaleFeeLoadId;
			}
			set
			{
				if ((this._PointOfSaleFeeLoadId != value))
				{
					this._PointOfSaleFeeLoadId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientTopUnitGuid", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string ClientTopUnitGuid
		{
			get
			{
				return this._ClientTopUnitGuid;
			}
			set
			{
				if ((this._ClientTopUnitGuid != value))
				{
					this._ClientTopUnitGuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientTopUnitName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ClientTopUnitName
		{
			get
			{
				return this._ClientTopUnitName;
			}
			set
			{
				if ((this._ClientTopUnitName != value))
				{
					this._ClientTopUnitName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientSubUnitGuid", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string ClientSubUnitGuid
		{
			get
			{
				return this._ClientSubUnitGuid;
			}
			set
			{
				if ((this._ClientSubUnitGuid != value))
				{
					this._ClientSubUnitGuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientSubUnitName", DbType="NVarChar(50)")]
		public string ClientSubUnitName
		{
			get
			{
				return this._ClientSubUnitName;
			}
			set
			{
				if ((this._ClientSubUnitName != value))
				{
					this._ClientSubUnitName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelerTypeGuid", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string TravelerTypeGuid
		{
			get
			{
				return this._TravelerTypeGuid;
			}
			set
			{
				if ((this._TravelerTypeGuid != value))
				{
					this._TravelerTypeGuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelerTypeName", DbType="VarChar(50)")]
		public string TravelerTypeName
		{
			get
			{
				return this._TravelerTypeName;
			}
			set
			{
				if ((this._TravelerTypeName != value))
				{
					this._TravelerTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeLoadDescriptionTypeCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FeeLoadDescriptionTypeCode
		{
			get
			{
				return this._FeeLoadDescriptionTypeCode;
			}
			set
			{
				if ((this._FeeLoadDescriptionTypeCode != value))
				{
					this._FeeLoadDescriptionTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int NOT NULL")]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentInitiatedFlag", DbType="Bit NOT NULL")]
		public bool AgentInitiatedFlag
		{
			get
			{
				return this._AgentInitiatedFlag;
			}
			set
			{
				if ((this._AgentInitiatedFlag != value))
				{
					this._AgentInitiatedFlag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelIndicator", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string TravelIndicator
		{
			get
			{
				return this._TravelIndicator;
			}
			set
			{
				if ((this._TravelIndicator != value))
				{
					this._TravelIndicator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeLoadAmount", DbType="Decimal(12,4) NOT NULL")]
		public decimal FeeLoadAmount
		{
			get
			{
				return this._FeeLoadAmount;
			}
			set
			{
				if ((this._FeeLoadAmount != value))
				{
					this._FeeLoadAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeLoadCurrencyCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string FeeLoadCurrencyCode
		{
			get
			{
				return this._FeeLoadCurrencyCode;
			}
			set
			{
				if ((this._FeeLoadCurrencyCode != value))
				{
					this._FeeLoadCurrencyCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasWriteAccess", DbType="Bit")]
		public System.Nullable<bool> HasWriteAccess
		{
			get
			{
				return this._HasWriteAccess;
			}
			set
			{
				if ((this._HasWriteAccess != value))
				{
					this._HasWriteAccess = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCount", DbType="Int")]
		public System.Nullable<int> RecordCount
		{
			get
			{
				return this._RecordCount;
			}
			set
			{
				if ((this._RecordCount != value))
				{
					this._RecordCount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
