<?xml version="1.0" encoding="utf-8"?><Database Name="Desktop_Local_v2031" Class="PolicyAdviceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DMLAPTOP2\SQL2008;Initial Catalog=Desktop_Local_v2031;User ID=cdoadmin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Desktop_Local_v2031" Provider="System.Data.SqlClient" />
</Database>