<?xml version="1.0" encoding="utf-8"?><Database Name="Desktop_Local_v1841" Class="PolicyGroupDC" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.11.90;Initial Catalog=Desktop_Local_v1841;Persist Security Info=True;User ID=cdoadmin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Desktop_Local_v1841" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PolicyGroupLocation" Member="PolicyGroupLocations">
    <Type Name="PolicyGroupLocation">
      <Column Name="LocationId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PolicyGroupId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SequenceNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="LastUpdateTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdateUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PolicyGroup_PolicyGroupLocation" Member="PolicyGroup" ThisKey="PolicyGroupId" OtherKey="PolicyGroupId" Type="PolicyGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PolicyGroupTeam" Member="PolicyGroupTeams">
    <Type Name="PolicyGroupTeam">
      <Column Name="PolicyGroupId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TeamId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SequenceNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="LastUpdateTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdateUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PolicyGroup_PolicyGroupTeam" Member="PolicyGroup" ThisKey="PolicyGroupId" OtherKey="PolicyGroupId" Type="PolicyGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PolicyGroup" Member="PolicyGroups">
    <Type Name="PolicyGroup">
      <Column Name="PolicyGroupId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PolicyGroupName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EnabledFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EnabledDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InheritFromParentFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TripTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletedFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="LastUpdateTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdateUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeetingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PolicyGroup_PolicyGroupLocation" Member="PolicyGroupLocations" ThisKey="PolicyGroupId" OtherKey="PolicyGroupId" Type="PolicyGroupLocation" />
      <Association Name="PolicyGroup_PolicyGroupTeam" Member="PolicyGroupTeams" ThisKey="PolicyGroupId" OtherKey="PolicyGroupId" Type="PolicyGroupTeam" />
      <Association Name="PolicyGroup_PolicyGroup" Member="PolicyGroup2" ThisKey="PolicyGroupId" OtherKey="PolicyGroupId" Type="PolicyGroup" Cardinality="One" />
      <Association Name="PolicyGroup_PolicyGroup" Member="PolicyGroup1" ThisKey="PolicyGroupId" OtherKey="PolicyGroupId" Type="PolicyGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.spDesktopDataAdmin_UpdatePolicyGroupDeletedStatus_v1" Method="spDesktopDataAdmin_UpdatePolicyGroupDeletedStatus_v1">
    <Parameter Name="PolicyGroupId" Parameter="policyGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Deleted" Parameter="deleted" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="VersionNumber" Parameter="versionNumber" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fnDesktopDataAdmin_SelectPolicyGroupHierarchy_v1" Method="fnDesktopDataAdmin_SelectPolicyGroupHierarchy_v1" IsComposable="true">
    <Parameter Name="PolicyGroupId" Parameter="policyGroupId" Type="System.Int32" DbType="Int" />
    <ElementType Name="fnDesktopDataAdmin_SelectPolicyGroupHierarchy_v1Result">
      <Column Name="SequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HierarchyCode" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="HierarchyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HierarchyType" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TravelerTypeGuid" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="TravelerTypeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SourceSystemCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_SelectPolicyGroups_v1" Method="spDesktopDataAdmin_SelectPolicyGroups_v1">
    <Parameter Name="DeletedFlag" Parameter="deletedFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Filter" Parameter="filter" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="SortField" Parameter="sortField" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SortOrder" Parameter="sortOrder" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageNumber" Parameter="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <ElementType Name="spDesktopDataAdmin_SelectPolicyGroups_v1Result">
      <Column Name="PolicyGroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyGroupName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LinkedItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HierarchyType" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="HasWriteAccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RecordCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_UpdatePolicyGroupLinkedClientSubUnit_v1" Method="spDesktopDataAdmin_UpdatePolicyGroupLinkedClientSubUnit_v1">
    <Parameter Name="PolicyGroupId" Parameter="policyGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClientSubUnitGuid" Parameter="clientSubUnitGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_SelectPolicyGroupsOrphaned_v1" Method="spDesktopDataAdmin_SelectPolicyGroupsOrphaned_v1">
    <Parameter Name="Filter" Parameter="filter" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="SortField" Parameter="sortField" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SortOrder" Parameter="sortOrder" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageNumber" Parameter="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <ElementType Name="spDesktopDataAdmin_SelectPolicyGroupsOrphaned_v1Result">
      <Column Name="PolicyGroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PolicyGroupName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DeletedFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasWriteAccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RecordCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_SelectPolicyGroupSubMenuCounts_v1" Method="spDesktopDataAdmin_SelectPolicyGroupSubMenuCounts_v1">
    <Parameter Name="PolicyGroupID" Parameter="policyGroupID" Type="System.Int32" DbType="Int" />
    <ElementType Name="spDesktopDataAdmin_SelectPolicyGroupSubMenuCounts_v1Result">
      <Column Name="PolicyAirCabinGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyAirMissedSavingsThresholdGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyAirVendorGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyCarTypeGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyCarVendorGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyCityGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyCountryGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyHotelCapRateGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyHotelPropertyItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyHotelVendorGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyMessageGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicySupplierDealCodeCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicySupplierServiceInformationCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyAirOtherGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyAllOtherGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyCarOtherGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyHotelOtherGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyOtherGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Policy24HSCOtherGroupItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_SelectPolicyTypes_v1" Method="spDesktopDataAdmin_SelectPolicyTypes_v1">
    <Parameter Name="PolicyGroupID" Parameter="policyGroupID" Type="System.Int32" DbType="Int" />
    <ElementType Name="spDesktopDataAdmin_SelectPolicyTypes_v1Result">
      <Column Name="PolicyTypeTableName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NavigationLinkPolicyTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_InsertPolicyGroup_v1" Method="spDesktopDataAdmin_InsertPolicyGroup_v1">
    <Parameter Name="PolicyGroupName" Parameter="policyGroupName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="EnabledFlag" Parameter="enabledFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EnabledDate" Parameter="enabledDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ExpiryDate" Parameter="expiryDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="InheritFromParentFlag" Parameter="inheritFromParentFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="TripTypeId" Parameter="tripTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="HierarchyType" Parameter="hierarchyType" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="HierarchyItemCode" Parameter="hierarchyItemCode" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="TravelerTypeGuid" Parameter="travelerTypeGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="ClientSubUnitGuid" Parameter="clientSubUnitGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="SourceSystemCode" Parameter="sourceSystemCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="MeetingID" Parameter="meetingID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_UpdatePolicyGroup_v1" Method="spDesktopDataAdmin_UpdatePolicyGroup_v1">
    <Parameter Name="PolicyGroupId" Parameter="policyGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PolicyGroupName" Parameter="policyGroupName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="EnabledFlag" Parameter="enabledFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EnabledDate" Parameter="enabledDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ExpiryDate" Parameter="expiryDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="InheritFromParentFlag" Parameter="inheritFromParentFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="TripTypeId" Parameter="tripTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="MeetingID" Parameter="meetingID" Type="System.Int32" DbType="Int" />
    <Parameter Name="HierarchyType" Parameter="hierarchyType" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="HierarchyItemCode" Parameter="hierarchyItemCode" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="TravelerTypeGuid" Parameter="travelerTypeGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="ClientSubUnitGuid" Parameter="clientSubUnitGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="SourceSystemCode" Parameter="sourceSystemCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="IsMultipleHierarchy" Parameter="isMultipleHierarchy" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="VersionNumber" Parameter="versionNumber" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_SelectPolicyGroupLinkedClientSubUnits_v1" Method="spDesktopDataAdmin_SelectPolicyGroupLinkedClientSubUnits_v1">
    <Parameter Name="PolicyGroupId" Parameter="policyGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="Linked" Parameter="linked" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="spDesktopDataAdmin_SelectPolicyGroupLinkedClientSubUnits_v1Result">
      <Column Name="ClientSubUnitGuid" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="ClientSubUnitName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HasWriteAccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsClientExpiredFlag" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>