#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Desktop_Local_v2031")]
	public partial class PolicyCountryGroupItemLanguageDC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPolicyCountryGroupItemLanguage(PolicyCountryGroupItemLanguage instance);
    partial void UpdatePolicyCountryGroupItemLanguage(PolicyCountryGroupItemLanguage instance);
    partial void DeletePolicyCountryGroupItemLanguage(PolicyCountryGroupItemLanguage instance);
    #endregion
		
		public PolicyCountryGroupItemLanguageDC() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Desktop_Local_v2031"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyCountryGroupItemLanguageDC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyCountryGroupItemLanguageDC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyCountryGroupItemLanguageDC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyCountryGroupItemLanguageDC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PolicyCountryGroupItemLanguage> PolicyCountryGroupItemLanguages
		{
			get
			{
				return this.GetTable<PolicyCountryGroupItemLanguage>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPolicyCountryGroupItemCountryAdvice_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPolicyCountryGroupItemCountryAdvice_v1Result> spDesktopDataAdmin_SelectPolicyCountryGroupItemCountryAdvice_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyCountryGroupItemId", DbType="Int")] System.Nullable<int> policyCountryGroupItemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortField", DbType="VarChar(50)")] string sortField, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyCountryGroupItemId, sortField, sortOrder, pageNumber);
			return ((ISingleResult<spDesktopDataAdmin_SelectPolicyCountryGroupItemCountryAdvice_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPolicyCountryGroupItemAvailableLanguages_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPolicyCountryGroupItemAvailableLanguages_v1Result> spDesktopDataAdmin_SelectPolicyCountryGroupItemAvailableLanguages_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyCountryGroupitemId", DbType="Int")] System.Nullable<int> policyCountryGroupitemId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyCountryGroupitemId);
			return ((ISingleResult<spDesktopDataAdmin_SelectPolicyCountryGroupItemAvailableLanguages_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_UpdatePolicyCountryGroupItemCountryAdvice_v1")]
		public int spDesktopDataAdmin_UpdatePolicyCountryGroupItemCountryAdvice_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyCountryGroupitemId", DbType="Int")] System.Nullable<int> policyCountryGroupitemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="NVarChar(5)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountryAdvice", DbType="NVarChar(255)")] string countryAdvice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyCountryGroupitemId, languageCode, countryAdvice, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_InsertPolicyCountryGroupItemCountryAdvice_v1")]
		public int spDesktopDataAdmin_InsertPolicyCountryGroupItemCountryAdvice_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyCountryGroupitemId", DbType="Int")] System.Nullable<int> policyCountryGroupitemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="NVarChar(5)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountryAdvice", DbType="NVarChar(255)")] string countryAdvice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyCountryGroupitemId, languageCode, countryAdvice, adminUserGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_DeletePolicyCountryGroupItemCountryAdvice_v1")]
		public int spDesktopDataAdmin_DeletePolicyCountryGroupItemCountryAdvice_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyCountryGroupitemId", DbType="Int")] System.Nullable<int> policyCountryGroupitemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="NVarChar(5)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyCountryGroupitemId, languageCode, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PolicyCountryGroupItemLanguage")]
	public partial class PolicyCountryGroupItemLanguage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PolicyCountryGroupItemId;
		
		private string _LanguageCode;
		
		private string _CountryAdvice;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private int _VersionNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPolicyCountryGroupItemIdChanging(int value);
    partial void OnPolicyCountryGroupItemIdChanged();
    partial void OnLanguageCodeChanging(string value);
    partial void OnLanguageCodeChanged();
    partial void OnCountryAdviceChanging(string value);
    partial void OnCountryAdviceChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(int value);
    partial void OnVersionNumberChanged();
    #endregion
		
		public PolicyCountryGroupItemLanguage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyCountryGroupItemId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PolicyCountryGroupItemId
		{
			get
			{
				return this._PolicyCountryGroupItemId;
			}
			set
			{
				if ((this._PolicyCountryGroupItemId != value))
				{
					this.OnPolicyCountryGroupItemIdChanging(value);
					this.SendPropertyChanging();
					this._PolicyCountryGroupItemId = value;
					this.SendPropertyChanged("PolicyCountryGroupItemId");
					this.OnPolicyCountryGroupItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this.OnLanguageCodeChanging(value);
					this.SendPropertyChanging();
					this._LanguageCode = value;
					this.SendPropertyChanged("LanguageCode");
					this.OnLanguageCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryAdvice", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string CountryAdvice
		{
			get
			{
				return this._CountryAdvice;
			}
			set
			{
				if ((this._CountryAdvice != value))
				{
					this.OnCountryAdviceChanging(value);
					this.SendPropertyChanging();
					this._CountryAdvice = value;
					this.SendPropertyChanged("CountryAdvice");
					this.OnCountryAdviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int NOT NULL")]
		public int VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPolicyCountryGroupItemCountryAdvice_v1Result
	{
		
		private int _PolicyCountryGroupItemId;
		
		private string _LanguageCode;
		
		private string _LanguageName;
		
		private string _CountryAdvice;
		
		private System.Nullable<int> _RecordCount;
		
		public spDesktopDataAdmin_SelectPolicyCountryGroupItemCountryAdvice_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyCountryGroupItemId", DbType="Int NOT NULL")]
		public int PolicyCountryGroupItemId
		{
			get
			{
				return this._PolicyCountryGroupItemId;
			}
			set
			{
				if ((this._PolicyCountryGroupItemId != value))
				{
					this._PolicyCountryGroupItemId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this._LanguageCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LanguageName
		{
			get
			{
				return this._LanguageName;
			}
			set
			{
				if ((this._LanguageName != value))
				{
					this._LanguageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryAdvice", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string CountryAdvice
		{
			get
			{
				return this._CountryAdvice;
			}
			set
			{
				if ((this._CountryAdvice != value))
				{
					this._CountryAdvice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCount", DbType="Int")]
		public System.Nullable<int> RecordCount
		{
			get
			{
				return this._RecordCount;
			}
			set
			{
				if ((this._RecordCount != value))
				{
					this._RecordCount = value;
				}
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPolicyCountryGroupItemAvailableLanguages_v1Result
	{
		
		private string _LanguageName;
		
		private string _LanguageCode;
		
		public spDesktopDataAdmin_SelectPolicyCountryGroupItemAvailableLanguages_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LanguageName
		{
			get
			{
				return this._LanguageName;
			}
			set
			{
				if ((this._LanguageName != value))
				{
					this._LanguageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this._LanguageCode = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
