#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DesktopData")]
	public partial class PolicyAirVendorGroupItemLanguageDC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPolicyAirVendorGroupItemLanguage(PolicyAirVendorGroupItemLanguage instance);
    partial void UpdatePolicyAirVendorGroupItemLanguage(PolicyAirVendorGroupItemLanguage instance);
    partial void DeletePolicyAirVendorGroupItemLanguage(PolicyAirVendorGroupItemLanguage instance);
    #endregion
		
		public PolicyAirVendorGroupItemLanguageDC() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CWTDesktopDatabase"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyAirVendorGroupItemLanguageDC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyAirVendorGroupItemLanguageDC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyAirVendorGroupItemLanguageDC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyAirVendorGroupItemLanguageDC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PolicyAirVendorGroupItemLanguage> PolicyAirVendorGroupItemLanguages
		{
			get
			{
				return this.GetTable<PolicyAirVendorGroupItemLanguage>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPolicyAirVendorGroupItemAvailableLanguages_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPolicyAirVendorGroupItemAvailableLanguages_v1Result> spDesktopDataAdmin_SelectPolicyAirVendorGroupItemAvailableLanguages_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirVendorGroupitemId", DbType="Int")] System.Nullable<int> policyAirVendorGroupitemId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirVendorGroupitemId);
			return ((ISingleResult<spDesktopDataAdmin_SelectPolicyAirVendorGroupItemAvailableLanguages_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_InsertPolicyAirVendorGroupItemAirlineAdvice_v1")]
		public int spDesktopDataAdmin_InsertPolicyAirVendorGroupItemAirlineAdvice_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirVendorGroupitemId", DbType="Int")] System.Nullable<int> policyAirVendorGroupitemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="NVarChar(5)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AirlineAdvice", DbType="NVarChar(50)")] string airlineAdvice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirVendorGroupitemId, languageCode, airlineAdvice, adminUserGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_UpdatePolicyAirVendorGroupItemAirlineAdvice_v1")]
		public int spDesktopDataAdmin_UpdatePolicyAirVendorGroupItemAirlineAdvice_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirVendorGroupitemId", DbType="Int")] System.Nullable<int> policyAirVendorGroupitemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="NVarChar(5)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AirlineAdvice", DbType="NVarChar(50)")] string airlineAdvice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirVendorGroupitemId, languageCode, airlineAdvice, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPolicyAirVendorGroupItemAirVendorAdvice_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPolicyAirVendorGroupItemAirVendorAdvice_v1Result> spDesktopDataAdmin_SelectPolicyAirVendorGroupItemAirVendorAdvice_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirVendorGroupItemId", DbType="Int")] System.Nullable<int> policyAirVendorGroupItemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortField", DbType="VarChar(50)")] string sortField, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirVendorGroupItemId, sortField, sortOrder, pageNumber);
			return ((ISingleResult<spDesktopDataAdmin_SelectPolicyAirVendorGroupItemAirVendorAdvice_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_DeletePolicyAirVendorGroupItemAirlineAdvice_v1")]
		public int spDesktopDataAdmin_DeletePolicyAirVendorGroupItemAirlineAdvice_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirVendorGroupitemId", DbType="Int")] System.Nullable<int> policyAirVendorGroupitemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="NVarChar(5)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirVendorGroupitemId, languageCode, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PolicyAirVendorGroupItemLanguage")]
	public partial class PolicyAirVendorGroupItemLanguage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PolicyAirVendorGroupItemId;
		
		private string _LanguageCode;
		
		private string _AirlineAdvice;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private System.Nullable<int> _VersionNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPolicyAirVendorGroupItemIdChanging(int value);
    partial void OnPolicyAirVendorGroupItemIdChanged();
    partial void OnLanguageCodeChanging(string value);
    partial void OnLanguageCodeChanged();
    partial void OnAirlineAdviceChanging(string value);
    partial void OnAirlineAdviceChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(System.Nullable<int> value);
    partial void OnVersionNumberChanged();
    #endregion
		
		public PolicyAirVendorGroupItemLanguage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyAirVendorGroupItemId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PolicyAirVendorGroupItemId
		{
			get
			{
				return this._PolicyAirVendorGroupItemId;
			}
			set
			{
				if ((this._PolicyAirVendorGroupItemId != value))
				{
					this.OnPolicyAirVendorGroupItemIdChanging(value);
					this.SendPropertyChanging();
					this._PolicyAirVendorGroupItemId = value;
					this.SendPropertyChanged("PolicyAirVendorGroupItemId");
					this.OnPolicyAirVendorGroupItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this.OnLanguageCodeChanging(value);
					this.SendPropertyChanging();
					this._LanguageCode = value;
					this.SendPropertyChanged("LanguageCode");
					this.OnLanguageCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AirlineAdvice", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AirlineAdvice
		{
			get
			{
				return this._AirlineAdvice;
			}
			set
			{
				if ((this._AirlineAdvice != value))
				{
					this.OnAirlineAdviceChanging(value);
					this.SendPropertyChanging();
					this._AirlineAdvice = value;
					this.SendPropertyChanged("AirlineAdvice");
					this.OnAirlineAdviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int")]
		public System.Nullable<int> VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPolicyAirVendorGroupItemAvailableLanguages_v1Result
	{
		
		private string _LanguageName;
		
		private string _LanguageCode;
		
		public spDesktopDataAdmin_SelectPolicyAirVendorGroupItemAvailableLanguages_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LanguageName
		{
			get
			{
				return this._LanguageName;
			}
			set
			{
				if ((this._LanguageName != value))
				{
					this._LanguageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this._LanguageCode = value;
				}
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPolicyAirVendorGroupItemAirVendorAdvice_v1Result
	{
		
		private int _PolicyAirVendorGroupItemId;
		
		private string _LanguageCode;
		
		private string _LanguageName;
		
		private string _AirlineAdvice;
		
		private System.Nullable<int> _RecordCount;
		
		public spDesktopDataAdmin_SelectPolicyAirVendorGroupItemAirVendorAdvice_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyAirVendorGroupItemId", DbType="Int NOT NULL")]
		public int PolicyAirVendorGroupItemId
		{
			get
			{
				return this._PolicyAirVendorGroupItemId;
			}
			set
			{
				if ((this._PolicyAirVendorGroupItemId != value))
				{
					this._PolicyAirVendorGroupItemId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this._LanguageCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LanguageName
		{
			get
			{
				return this._LanguageName;
			}
			set
			{
				if ((this._LanguageName != value))
				{
					this._LanguageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AirlineAdvice", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AirlineAdvice
		{
			get
			{
				return this._AirlineAdvice;
			}
			set
			{
				if ((this._AirlineAdvice != value))
				{
					this._AirlineAdvice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCount", DbType="Int")]
		public System.Nullable<int> RecordCount
		{
			get
			{
				return this._RecordCount;
			}
			set
			{
				if ((this._RecordCount != value))
				{
					this._RecordCount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
