#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Desktop_Local_v1851")]
	public partial class PolicyAirCabinGroupItemDC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPolicyAirCabinGroupItem(PolicyAirCabinGroupItem instance);
    partial void UpdatePolicyAirCabinGroupItem(PolicyAirCabinGroupItem instance);
    partial void DeletePolicyAirCabinGroupItem(PolicyAirCabinGroupItem instance);
    partial void InsertPolicyAirCabinGroupItemLanguage(PolicyAirCabinGroupItemLanguage instance);
    partial void UpdatePolicyAirCabinGroupItemLanguage(PolicyAirCabinGroupItemLanguage instance);
    partial void DeletePolicyAirCabinGroupItemLanguage(PolicyAirCabinGroupItemLanguage instance);
    #endregion
		
		public PolicyAirCabinGroupItemDC() : 
				base(global::CWTDesktopDatabase.Properties.Settings.Default.Desktop_Local_v1851ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyAirCabinGroupItemDC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyAirCabinGroupItemDC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyAirCabinGroupItemDC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyAirCabinGroupItemDC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PolicyAirCabinGroupItem> PolicyAirCabinGroupItems
		{
			get
			{
				return this.GetTable<PolicyAirCabinGroupItem>();
			}
		}
		
		public System.Data.Linq.Table<PolicyAirCabinGroupItemLanguage> PolicyAirCabinGroupItemLanguages
		{
			get
			{
				return this.GetTable<PolicyAirCabinGroupItemLanguage>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_DeletePolicyAirCabinGroupItem_v1")]
		public int spDesktopDataAdmin_DeletePolicyAirCabinGroupItem_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirCabinGroupItemId", DbType="Int")] System.Nullable<int> policyAirCabinGroupItemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirCabinGroupItemId, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_InsertPolicyAirCabinGroupItem_v1")]
		public int spDesktopDataAdmin_InsertPolicyAirCabinGroupItem_v1(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirCabinGroupItemId", DbType="Int")] ref System.Nullable<int> policyAirCabinGroupItemId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyGroupId", DbType="Int")] System.Nullable<int> policyGroupId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AirlineCabinCode", DbType="NVarChar(2)")] string airlineCabinCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FlightDurationAllowedMin", DbType="Int")] System.Nullable<int> flightDurationAllowedMin, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FlightDurationAllowedMax", DbType="Int")] System.Nullable<int> flightDurationAllowedMax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FlightMileageAllowedMin", DbType="Int")] System.Nullable<int> flightMileageAllowedMin, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FlightMileageAllowedMax", DbType="Int")] System.Nullable<int> flightMileageAllowedMax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyProhibitedFlag", DbType="Bit")] System.Nullable<bool> policyProhibitedFlag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledFlag", DbType="Bit")] System.Nullable<bool> enabledFlag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledDate", DbType="DateTime")] System.Nullable<System.DateTime> enabledDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpiryDate", DbType="DateTime")] System.Nullable<System.DateTime> expiryDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelDateValidFrom", DbType="DateTime")] System.Nullable<System.DateTime> travelDateValidFrom, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelDateValidTo", DbType="DateTime")] System.Nullable<System.DateTime> travelDateValidTo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(100)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromGlobalFlag", DbType="Bit")] System.Nullable<bool> fromGlobalFlag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromGlobalRegionCode", DbType="VarChar(5)")] string fromGlobalRegionCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromGlobalSubRegionCode", DbType="VarChar(5)")] string fromGlobalSubRegionCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromCountryCode", DbType="VarChar(2)")] string fromCountryCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromCityCode", DbType="NVarChar(5)")] string fromCityCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromTravelPortCode", DbType="NVarChar(50)")] string fromTravelPortCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromTraverlPortTypeId", DbType="Int")] System.Nullable<int> fromTraverlPortTypeId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToGlobalFlag", DbType="Bit")] System.Nullable<bool> toGlobalFlag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToGlobalRegionCode", DbType="VarChar(5)")] string toGlobalRegionCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToGlobalSubRegionCode", DbType="VarChar(5)")] string toGlobalSubRegionCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToCountryCode", DbType="VarChar(2)")] string toCountryCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToCityCode", DbType="NVarChar(5)")] string toCityCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToTravelPortCode", DbType="NVarChar(50)")] string toTravelPortCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToTravelPortTypeId", DbType="NChar(10)")] string toTravelPortTypeId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoutingViceVersaFlag", DbType="Bit")] System.Nullable<bool> routingViceVersaFlag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirCabinGroupItemId, policyGroupId, airlineCabinCode, flightDurationAllowedMin, flightDurationAllowedMax, flightMileageAllowedMin, flightMileageAllowedMax, policyProhibitedFlag, enabledFlag, enabledDate, expiryDate, travelDateValidFrom, travelDateValidTo, name, fromGlobalFlag, fromGlobalRegionCode, fromGlobalSubRegionCode, fromCountryCode, fromCityCode, fromTravelPortCode, fromTraverlPortTypeId, toGlobalFlag, toGlobalRegionCode, toGlobalSubRegionCode, toCountryCode, toCityCode, toTravelPortCode, toTravelPortTypeId, routingViceVersaFlag, adminUserGuid);
			policyAirCabinGroupItemId = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_UpdatePolicyAirCabinGroupItem_v1")]
		public int spDesktopDataAdmin_UpdatePolicyAirCabinGroupItem_v1(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirCabinGroupItemId", DbType="Int")] System.Nullable<int> policyAirCabinGroupItemId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyGroupId", DbType="Int")] System.Nullable<int> policyGroupId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AirlineCabinCode", DbType="NVarChar(2)")] string airlineCabinCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FlightDurationAllowedMin", DbType="Int")] System.Nullable<int> flightDurationAllowedMin, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FlightDurationAllowedMax", DbType="Int")] System.Nullable<int> flightDurationAllowedMax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FlightMileageAllowedMin", DbType="Int")] System.Nullable<int> flightMileageAllowedMin, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FlightMileageAllowedMax", DbType="Int")] System.Nullable<int> flightMileageAllowedMax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyProhibitedFlag", DbType="Bit")] System.Nullable<bool> policyProhibitedFlag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledFlag", DbType="Bit")] System.Nullable<bool> enabledFlag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledDate", DbType="DateTime")] System.Nullable<System.DateTime> enabledDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpiryDate", DbType="DateTime")] System.Nullable<System.DateTime> expiryDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelDateValidFrom", DbType="DateTime")] System.Nullable<System.DateTime> travelDateValidFrom, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelDateValidTo", DbType="DateTime")] System.Nullable<System.DateTime> travelDateValidTo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(100)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromGlobalFlag", DbType="Bit")] System.Nullable<bool> fromGlobalFlag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromGlobalRegionCode", DbType="VarChar(5)")] string fromGlobalRegionCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromGlobalSubRegionCode", DbType="VarChar(5)")] string fromGlobalSubRegionCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromCountryCode", DbType="VarChar(2)")] string fromCountryCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromCityCode", DbType="NVarChar(5)")] string fromCityCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromTravelPortCode", DbType="NVarChar(50)")] string fromTravelPortCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromTraverlPortTypeId", DbType="Int")] System.Nullable<int> fromTraverlPortTypeId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToGlobalFlag", DbType="Bit")] System.Nullable<bool> toGlobalFlag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToGlobalRegionCode", DbType="VarChar(5)")] string toGlobalRegionCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToGlobalSubRegionCode", DbType="VarChar(5)")] string toGlobalSubRegionCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToCountryCode", DbType="VarChar(2)")] string toCountryCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToCityCode", DbType="NVarChar(5)")] string toCityCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToTravelPortCode", DbType="NVarChar(50)")] string toTravelPortCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToTravelPortTypeId", DbType="NChar(10)")] string toTravelPortTypeId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoutingViceVersaFlag", DbType="Bit")] System.Nullable<bool> routingViceVersaFlag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirCabinGroupItemId, policyGroupId, airlineCabinCode, flightDurationAllowedMin, flightDurationAllowedMax, flightMileageAllowedMin, flightMileageAllowedMax, policyProhibitedFlag, enabledFlag, enabledDate, expiryDate, travelDateValidFrom, travelDateValidTo, name, fromGlobalFlag, fromGlobalRegionCode, fromGlobalSubRegionCode, fromCountryCode, fromCityCode, fromTravelPortCode, fromTraverlPortTypeId, toGlobalFlag, toGlobalRegionCode, toGlobalSubRegionCode, toCountryCode, toCityCode, toTravelPortCode, toTravelPortTypeId, routingViceVersaFlag, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_InsertPolicyAirCabinGroupItemAirCabinAdvice_v1")]
		public int spDesktopDataAdmin_InsertPolicyAirCabinGroupItemAirCabinAdvice_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirCabinGroupitemId", DbType="Int")] System.Nullable<int> policyAirCabinGroupitemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="NVarChar(5)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AirCabinAdvice", DbType="NVarChar(255)")] string airCabinAdvice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirCabinGroupitemId, languageCode, airCabinAdvice, adminUserGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAirCabinAdvice_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAirCabinAdvice_v1Result> spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAirCabinAdvice_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirCabinGroupItemId", DbType="Int")] System.Nullable<int> policyAirCabinGroupItemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortField", DbType="VarChar(50)")] string sortField, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirCabinGroupItemId, sortField, sortOrder, pageNumber);
			return ((ISingleResult<spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAirCabinAdvice_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_DeletePolicyAirCabinGroupItemAirCabinAdvice_v1")]
		public int spDesktopDataAdmin_DeletePolicyAirCabinGroupItemAirCabinAdvice_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirCabinGroupitemId", DbType="Int")] System.Nullable<int> policyAirCabinGroupitemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="NVarChar(5)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirCabinGroupitemId, languageCode, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_UpdatePolicyAirCabinGroupItemAirCabinAdvice_v1")]
		public int spDesktopDataAdmin_UpdatePolicyAirCabinGroupItemAirCabinAdvice_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirCabinGroupitemId", DbType="Int")] System.Nullable<int> policyAirCabinGroupitemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="NVarChar(5)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AirCabinAdvice", DbType="NVarChar(255)")] string airCabinAdvice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirCabinGroupitemId, languageCode, airCabinAdvice, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAvailableLanguages_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAvailableLanguages_v1Result> spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAvailableLanguages_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirCabinGroupitemId", DbType="Int")] System.Nullable<int> policyAirCabinGroupitemId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirCabinGroupitemId);
			return ((ISingleResult<spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAvailableLanguages_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPolicyAirCabinGroupItems_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPolicyAirCabinGroupItems_v1Result> spDesktopDataAdmin_SelectPolicyAirCabinGroupItems_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyGroupID", DbType="Int")] System.Nullable<int> policyGroupID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SystemUserGuid", DbType="VarChar(13)")] string systemUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortField", DbType="VarChar(50)")] string sortField, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Bit")] System.Nullable<bool> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyGroupID, systemUserGuid, sortField, sortOrder, pageNumber);
			return ((ISingleResult<spDesktopDataAdmin_SelectPolicyAirCabinGroupItems_v1Result>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PolicyAirCabinGroupItem")]
	public partial class PolicyAirCabinGroupItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PolicyAirCabinGroupItemId;
		
		private int _PolicyGroupId;
		
		private string _AirlineCabinCode;
		
		private System.Nullable<int> _FlightDurationAllowedMin;
		
		private System.Nullable<int> _FlightDurationAllowedMax;
		
		private System.Nullable<int> _PolicyRoutingId;
		
		private bool _PolicyProhibitedFlag;
		
		private bool _EnabledFlag;
		
		private System.Nullable<System.DateTime> _EnabledDate;
		
		private System.Nullable<System.DateTime> _ExpiryDate;
		
		private System.Nullable<System.DateTime> _TravelDateValidFrom;
		
		private System.Nullable<System.DateTime> _TravelDateValidTo;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private int _VersionNumber;
		
		private System.Nullable<int> _FlightMileageAllowedMin;
		
		private System.Nullable<int> _FlightMileageAllowedMax;
		
		private EntitySet<PolicyAirCabinGroupItemLanguage> _PolicyAirCabinGroupItemLanguages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPolicyAirCabinGroupItemIdChanging(int value);
    partial void OnPolicyAirCabinGroupItemIdChanged();
    partial void OnPolicyGroupIdChanging(int value);
    partial void OnPolicyGroupIdChanged();
    partial void OnAirlineCabinCodeChanging(string value);
    partial void OnAirlineCabinCodeChanged();
    partial void OnFlightDurationAllowedMinChanging(System.Nullable<int> value);
    partial void OnFlightDurationAllowedMinChanged();
    partial void OnFlightDurationAllowedMaxChanging(System.Nullable<int> value);
    partial void OnFlightDurationAllowedMaxChanged();
    partial void OnPolicyRoutingIdChanging(System.Nullable<int> value);
    partial void OnPolicyRoutingIdChanged();
    partial void OnPolicyProhibitedFlagChanging(bool value);
    partial void OnPolicyProhibitedFlagChanged();
    partial void OnEnabledFlagChanging(bool value);
    partial void OnEnabledFlagChanged();
    partial void OnEnabledDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnabledDateChanged();
    partial void OnExpiryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpiryDateChanged();
    partial void OnTravelDateValidFromChanging(System.Nullable<System.DateTime> value);
    partial void OnTravelDateValidFromChanged();
    partial void OnTravelDateValidToChanging(System.Nullable<System.DateTime> value);
    partial void OnTravelDateValidToChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(int value);
    partial void OnVersionNumberChanged();
    partial void OnFlightMileageAllowedMinChanging(System.Nullable<int> value);
    partial void OnFlightMileageAllowedMinChanged();
    partial void OnFlightMileageAllowedMaxChanging(System.Nullable<int> value);
    partial void OnFlightMileageAllowedMaxChanged();
    #endregion
		
		public PolicyAirCabinGroupItem()
		{
			this._PolicyAirCabinGroupItemLanguages = new EntitySet<PolicyAirCabinGroupItemLanguage>(new Action<PolicyAirCabinGroupItemLanguage>(this.attach_PolicyAirCabinGroupItemLanguages), new Action<PolicyAirCabinGroupItemLanguage>(this.detach_PolicyAirCabinGroupItemLanguages));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyAirCabinGroupItemId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PolicyAirCabinGroupItemId
		{
			get
			{
				return this._PolicyAirCabinGroupItemId;
			}
			set
			{
				if ((this._PolicyAirCabinGroupItemId != value))
				{
					this.OnPolicyAirCabinGroupItemIdChanging(value);
					this.SendPropertyChanging();
					this._PolicyAirCabinGroupItemId = value;
					this.SendPropertyChanged("PolicyAirCabinGroupItemId");
					this.OnPolicyAirCabinGroupItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyGroupId", DbType="Int NOT NULL")]
		public int PolicyGroupId
		{
			get
			{
				return this._PolicyGroupId;
			}
			set
			{
				if ((this._PolicyGroupId != value))
				{
					this.OnPolicyGroupIdChanging(value);
					this.SendPropertyChanging();
					this._PolicyGroupId = value;
					this.SendPropertyChanged("PolicyGroupId");
					this.OnPolicyGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AirlineCabinCode", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string AirlineCabinCode
		{
			get
			{
				return this._AirlineCabinCode;
			}
			set
			{
				if ((this._AirlineCabinCode != value))
				{
					this.OnAirlineCabinCodeChanging(value);
					this.SendPropertyChanging();
					this._AirlineCabinCode = value;
					this.SendPropertyChanged("AirlineCabinCode");
					this.OnAirlineCabinCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightDurationAllowedMin", DbType="Int")]
		public System.Nullable<int> FlightDurationAllowedMin
		{
			get
			{
				return this._FlightDurationAllowedMin;
			}
			set
			{
				if ((this._FlightDurationAllowedMin != value))
				{
					this.OnFlightDurationAllowedMinChanging(value);
					this.SendPropertyChanging();
					this._FlightDurationAllowedMin = value;
					this.SendPropertyChanged("FlightDurationAllowedMin");
					this.OnFlightDurationAllowedMinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightDurationAllowedMax", DbType="Int")]
		public System.Nullable<int> FlightDurationAllowedMax
		{
			get
			{
				return this._FlightDurationAllowedMax;
			}
			set
			{
				if ((this._FlightDurationAllowedMax != value))
				{
					this.OnFlightDurationAllowedMaxChanging(value);
					this.SendPropertyChanging();
					this._FlightDurationAllowedMax = value;
					this.SendPropertyChanged("FlightDurationAllowedMax");
					this.OnFlightDurationAllowedMaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyRoutingId", DbType="Int")]
		public System.Nullable<int> PolicyRoutingId
		{
			get
			{
				return this._PolicyRoutingId;
			}
			set
			{
				if ((this._PolicyRoutingId != value))
				{
					this.OnPolicyRoutingIdChanging(value);
					this.SendPropertyChanging();
					this._PolicyRoutingId = value;
					this.SendPropertyChanged("PolicyRoutingId");
					this.OnPolicyRoutingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyProhibitedFlag", DbType="Bit NOT NULL")]
		public bool PolicyProhibitedFlag
		{
			get
			{
				return this._PolicyProhibitedFlag;
			}
			set
			{
				if ((this._PolicyProhibitedFlag != value))
				{
					this.OnPolicyProhibitedFlagChanging(value);
					this.SendPropertyChanging();
					this._PolicyProhibitedFlag = value;
					this.SendPropertyChanged("PolicyProhibitedFlag");
					this.OnPolicyProhibitedFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnabledFlag", DbType="Bit NOT NULL")]
		public bool EnabledFlag
		{
			get
			{
				return this._EnabledFlag;
			}
			set
			{
				if ((this._EnabledFlag != value))
				{
					this.OnEnabledFlagChanging(value);
					this.SendPropertyChanging();
					this._EnabledFlag = value;
					this.SendPropertyChanged("EnabledFlag");
					this.OnEnabledFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnabledDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EnabledDate
		{
			get
			{
				return this._EnabledDate;
			}
			set
			{
				if ((this._EnabledDate != value))
				{
					this.OnEnabledDateChanging(value);
					this.SendPropertyChanging();
					this._EnabledDate = value;
					this.SendPropertyChanged("EnabledDate");
					this.OnEnabledDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpiryDate
		{
			get
			{
				return this._ExpiryDate;
			}
			set
			{
				if ((this._ExpiryDate != value))
				{
					this.OnExpiryDateChanging(value);
					this.SendPropertyChanging();
					this._ExpiryDate = value;
					this.SendPropertyChanged("ExpiryDate");
					this.OnExpiryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelDateValidFrom", DbType="DateTime")]
		public System.Nullable<System.DateTime> TravelDateValidFrom
		{
			get
			{
				return this._TravelDateValidFrom;
			}
			set
			{
				if ((this._TravelDateValidFrom != value))
				{
					this.OnTravelDateValidFromChanging(value);
					this.SendPropertyChanging();
					this._TravelDateValidFrom = value;
					this.SendPropertyChanged("TravelDateValidFrom");
					this.OnTravelDateValidFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelDateValidTo", DbType="DateTime")]
		public System.Nullable<System.DateTime> TravelDateValidTo
		{
			get
			{
				return this._TravelDateValidTo;
			}
			set
			{
				if ((this._TravelDateValidTo != value))
				{
					this.OnTravelDateValidToChanging(value);
					this.SendPropertyChanging();
					this._TravelDateValidTo = value;
					this.SendPropertyChanged("TravelDateValidTo");
					this.OnTravelDateValidToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int NOT NULL")]
		public int VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightMileageAllowedMin", DbType="Int")]
		public System.Nullable<int> FlightMileageAllowedMin
		{
			get
			{
				return this._FlightMileageAllowedMin;
			}
			set
			{
				if ((this._FlightMileageAllowedMin != value))
				{
					this.OnFlightMileageAllowedMinChanging(value);
					this.SendPropertyChanging();
					this._FlightMileageAllowedMin = value;
					this.SendPropertyChanged("FlightMileageAllowedMin");
					this.OnFlightMileageAllowedMinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightMileageAllowedMax", DbType="Int")]
		public System.Nullable<int> FlightMileageAllowedMax
		{
			get
			{
				return this._FlightMileageAllowedMax;
			}
			set
			{
				if ((this._FlightMileageAllowedMax != value))
				{
					this.OnFlightMileageAllowedMaxChanging(value);
					this.SendPropertyChanging();
					this._FlightMileageAllowedMax = value;
					this.SendPropertyChanged("FlightMileageAllowedMax");
					this.OnFlightMileageAllowedMaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PolicyAirCabinGroupItem_PolicyAirCabinGroupItemLanguage", Storage="_PolicyAirCabinGroupItemLanguages", ThisKey="PolicyAirCabinGroupItemId", OtherKey="PolicyAirCabinGroupItemId")]
		public EntitySet<PolicyAirCabinGroupItemLanguage> PolicyAirCabinGroupItemLanguages
		{
			get
			{
				return this._PolicyAirCabinGroupItemLanguages;
			}
			set
			{
				this._PolicyAirCabinGroupItemLanguages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PolicyAirCabinGroupItemLanguages(PolicyAirCabinGroupItemLanguage entity)
		{
			this.SendPropertyChanging();
			entity.PolicyAirCabinGroupItem = this;
		}
		
		private void detach_PolicyAirCabinGroupItemLanguages(PolicyAirCabinGroupItemLanguage entity)
		{
			this.SendPropertyChanging();
			entity.PolicyAirCabinGroupItem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PolicyAirCabinGroupItemLanguage")]
	public partial class PolicyAirCabinGroupItemLanguage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PolicyAirCabinGroupItemId;
		
		private string _LanguageCode;
		
		private string _AirCabinAdvice;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private int _VersionNumber;
		
		private EntityRef<PolicyAirCabinGroupItem> _PolicyAirCabinGroupItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPolicyAirCabinGroupItemIdChanging(int value);
    partial void OnPolicyAirCabinGroupItemIdChanged();
    partial void OnLanguageCodeChanging(string value);
    partial void OnLanguageCodeChanged();
    partial void OnAirCabinAdviceChanging(string value);
    partial void OnAirCabinAdviceChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(int value);
    partial void OnVersionNumberChanged();
    #endregion
		
		public PolicyAirCabinGroupItemLanguage()
		{
			this._PolicyAirCabinGroupItem = default(EntityRef<PolicyAirCabinGroupItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyAirCabinGroupItemId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PolicyAirCabinGroupItemId
		{
			get
			{
				return this._PolicyAirCabinGroupItemId;
			}
			set
			{
				if ((this._PolicyAirCabinGroupItemId != value))
				{
					if (this._PolicyAirCabinGroupItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPolicyAirCabinGroupItemIdChanging(value);
					this.SendPropertyChanging();
					this._PolicyAirCabinGroupItemId = value;
					this.SendPropertyChanged("PolicyAirCabinGroupItemId");
					this.OnPolicyAirCabinGroupItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this.OnLanguageCodeChanging(value);
					this.SendPropertyChanging();
					this._LanguageCode = value;
					this.SendPropertyChanged("LanguageCode");
					this.OnLanguageCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AirCabinAdvice", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string AirCabinAdvice
		{
			get
			{
				return this._AirCabinAdvice;
			}
			set
			{
				if ((this._AirCabinAdvice != value))
				{
					this.OnAirCabinAdviceChanging(value);
					this.SendPropertyChanging();
					this._AirCabinAdvice = value;
					this.SendPropertyChanged("AirCabinAdvice");
					this.OnAirCabinAdviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int NOT NULL")]
		public int VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PolicyAirCabinGroupItem_PolicyAirCabinGroupItemLanguage", Storage="_PolicyAirCabinGroupItem", ThisKey="PolicyAirCabinGroupItemId", OtherKey="PolicyAirCabinGroupItemId", IsForeignKey=true)]
		public PolicyAirCabinGroupItem PolicyAirCabinGroupItem
		{
			get
			{
				return this._PolicyAirCabinGroupItem.Entity;
			}
			set
			{
				PolicyAirCabinGroupItem previousValue = this._PolicyAirCabinGroupItem.Entity;
				if (((previousValue != value) 
							|| (this._PolicyAirCabinGroupItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PolicyAirCabinGroupItem.Entity = null;
						previousValue.PolicyAirCabinGroupItemLanguages.Remove(this);
					}
					this._PolicyAirCabinGroupItem.Entity = value;
					if ((value != null))
					{
						value.PolicyAirCabinGroupItemLanguages.Add(this);
						this._PolicyAirCabinGroupItemId = value.PolicyAirCabinGroupItemId;
					}
					else
					{
						this._PolicyAirCabinGroupItemId = default(int);
					}
					this.SendPropertyChanged("PolicyAirCabinGroupItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAirCabinAdvice_v1Result
	{
		
		private int _PolicyAirCabinGroupItemId;
		
		private string _LanguageCode;
		
		private string _LanguageName;
		
		private string _AirCabinAdvice;
		
		private System.Nullable<int> _RecordCount;
		
		public spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAirCabinAdvice_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyAirCabinGroupItemId", DbType="Int NOT NULL")]
		public int PolicyAirCabinGroupItemId
		{
			get
			{
				return this._PolicyAirCabinGroupItemId;
			}
			set
			{
				if ((this._PolicyAirCabinGroupItemId != value))
				{
					this._PolicyAirCabinGroupItemId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this._LanguageCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LanguageName
		{
			get
			{
				return this._LanguageName;
			}
			set
			{
				if ((this._LanguageName != value))
				{
					this._LanguageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AirCabinAdvice", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string AirCabinAdvice
		{
			get
			{
				return this._AirCabinAdvice;
			}
			set
			{
				if ((this._AirCabinAdvice != value))
				{
					this._AirCabinAdvice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCount", DbType="Int")]
		public System.Nullable<int> RecordCount
		{
			get
			{
				return this._RecordCount;
			}
			set
			{
				if ((this._RecordCount != value))
				{
					this._RecordCount = value;
				}
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAvailableLanguages_v1Result
	{
		
		private string _LanguageName;
		
		private string _LanguageCode;
		
		public spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAvailableLanguages_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LanguageName
		{
			get
			{
				return this._LanguageName;
			}
			set
			{
				if ((this._LanguageName != value))
				{
					this._LanguageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this._LanguageCode = value;
				}
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPolicyAirCabinGroupItems_v1Result
	{
		
		private System.Nullable<int> _PolicyGroupId;
		
		private int _PolicyAirCabinGroupItemId;
		
		private System.Nullable<int> _FlightDurationAllowedMin;
		
		private System.Nullable<int> _FlightDurationAllowedMax;
		
		private System.Nullable<int> _FlightMileageAllowedMin;
		
		private System.Nullable<int> _FlightMileageAllowedMax;
		
		private string _Name;
		
		private string _AirlineCabinDefaultDescription;
		
		private System.Nullable<int> _Advice;
		
		private System.Nullable<bool> _HasWriteAccess;
		
		private System.Nullable<int> _RecordCount;
		
		public spDesktopDataAdmin_SelectPolicyAirCabinGroupItems_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyGroupId", DbType="Int")]
		public System.Nullable<int> PolicyGroupId
		{
			get
			{
				return this._PolicyGroupId;
			}
			set
			{
				if ((this._PolicyGroupId != value))
				{
					this._PolicyGroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyAirCabinGroupItemId", DbType="Int NOT NULL")]
		public int PolicyAirCabinGroupItemId
		{
			get
			{
				return this._PolicyAirCabinGroupItemId;
			}
			set
			{
				if ((this._PolicyAirCabinGroupItemId != value))
				{
					this._PolicyAirCabinGroupItemId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightDurationAllowedMin", DbType="Int")]
		public System.Nullable<int> FlightDurationAllowedMin
		{
			get
			{
				return this._FlightDurationAllowedMin;
			}
			set
			{
				if ((this._FlightDurationAllowedMin != value))
				{
					this._FlightDurationAllowedMin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightDurationAllowedMax", DbType="Int")]
		public System.Nullable<int> FlightDurationAllowedMax
		{
			get
			{
				return this._FlightDurationAllowedMax;
			}
			set
			{
				if ((this._FlightDurationAllowedMax != value))
				{
					this._FlightDurationAllowedMax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightMileageAllowedMin", DbType="Int")]
		public System.Nullable<int> FlightMileageAllowedMin
		{
			get
			{
				return this._FlightMileageAllowedMin;
			}
			set
			{
				if ((this._FlightMileageAllowedMin != value))
				{
					this._FlightMileageAllowedMin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightMileageAllowedMax", DbType="Int")]
		public System.Nullable<int> FlightMileageAllowedMax
		{
			get
			{
				return this._FlightMileageAllowedMax;
			}
			set
			{
				if ((this._FlightMileageAllowedMax != value))
				{
					this._FlightMileageAllowedMax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AirlineCabinDefaultDescription", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string AirlineCabinDefaultDescription
		{
			get
			{
				return this._AirlineCabinDefaultDescription;
			}
			set
			{
				if ((this._AirlineCabinDefaultDescription != value))
				{
					this._AirlineCabinDefaultDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advice", DbType="Int")]
		public System.Nullable<int> Advice
		{
			get
			{
				return this._Advice;
			}
			set
			{
				if ((this._Advice != value))
				{
					this._Advice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasWriteAccess", DbType="Bit")]
		public System.Nullable<bool> HasWriteAccess
		{
			get
			{
				return this._HasWriteAccess;
			}
			set
			{
				if ((this._HasWriteAccess != value))
				{
					this._HasWriteAccess = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCount", DbType="Int")]
		public System.Nullable<int> RecordCount
		{
			get
			{
				return this._RecordCount;
			}
			set
			{
				if ((this._RecordCount != value))
				{
					this._RecordCount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
