#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Desktop_Local_v1851")]
	public partial class PolicySupplierDealCodeDC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPolicySupplierDealCodeOSI(PolicySupplierDealCodeOSI instance);
    partial void UpdatePolicySupplierDealCodeOSI(PolicySupplierDealCodeOSI instance);
    partial void DeletePolicySupplierDealCodeOSI(PolicySupplierDealCodeOSI instance);
    partial void InsertPolicySupplierDealCode(PolicySupplierDealCode instance);
    partial void UpdatePolicySupplierDealCode(PolicySupplierDealCode instance);
    partial void DeletePolicySupplierDealCode(PolicySupplierDealCode instance);
    #endregion
		
		public PolicySupplierDealCodeDC() : 
				base(global::CWTDesktopDatabase.Properties.Settings.Default.Desktop_Local_v1851ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PolicySupplierDealCodeDC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicySupplierDealCodeDC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicySupplierDealCodeDC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicySupplierDealCodeDC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PolicySupplierDealCodeOSI> PolicySupplierDealCodeOSIs
		{
			get
			{
				return this.GetTable<PolicySupplierDealCodeOSI>();
			}
		}
		
		public System.Data.Linq.Table<PolicySupplierDealCode> PolicySupplierDealCodes
		{
			get
			{
				return this.GetTable<PolicySupplierDealCode>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_DeletePolicySupplierDealCode_v1")]
		public int spDesktopDataAdmin_DeletePolicySupplierDealCode_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicySupplierDealCodeId", DbType="Int")] System.Nullable<int> policySupplierDealCodeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policySupplierDealCodeId, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPolicySupplierDealCodes_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPolicySupplierDealCodes_v1Result> spDesktopDataAdmin_SelectPolicySupplierDealCodes_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyGroupId", DbType="Int")] System.Nullable<int> policyGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortField", DbType="VarChar(50)")] string sortField, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyGroupId, sortField, sortOrder, pageNumber);
			return ((ISingleResult<spDesktopDataAdmin_SelectPolicySupplierDealCodes_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_InsertPolicySupplierDealCode_v1")]
		public int spDesktopDataAdmin_InsertPolicySupplierDealCode_v1(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierCode", DbType="NVarChar(50)")] string supplierCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicySupplierDealCodeValue", DbType="NVarChar(50)")] string policySupplierDealCodeValue, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicySupplierDealCodeDescription", DbType="NVarChar(50)")] string policySupplierDealCodeDescription, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GDSCode", DbType="VarChar(4)")] string gDSCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicySupplierDealCodeTypeId", DbType="Int")] System.Nullable<int> policySupplierDealCodeTypeId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyGroupId", DbType="Int")] System.Nullable<int> policyGroupId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledFlag", DbType="Bit")] System.Nullable<bool> enabledFlag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledDate", DbType="DateTime")] System.Nullable<System.DateTime> enabledDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyLocationId", DbType="Int")] System.Nullable<int> policyLocationId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpiryDate", DbType="DateTime")] System.Nullable<System.DateTime> expiryDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelIndicator", DbType="VarChar(1)")] string travelIndicator, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TourCodeTypeId", DbType="Int")] System.Nullable<int> tourCodeTypeId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Endorsement", DbType="NVarChar(120)")] string endorsement, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndorsementOverride", DbType="NVarChar(120)")] string endorsementOverride, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OSIFlag", DbType="Bit")] System.Nullable<bool> oSIFlag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicySupplierDealCodeOSIXML", DbType="Xml")] System.Xml.Linq.XElement policySupplierDealCodeOSIXML, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), supplierCode, policySupplierDealCodeValue, policySupplierDealCodeDescription, gDSCode, productId, policySupplierDealCodeTypeId, policyGroupId, enabledFlag, enabledDate, policyLocationId, expiryDate, travelIndicator, tourCodeTypeId, endorsement, endorsementOverride, oSIFlag, policySupplierDealCodeOSIXML, adminUserGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_UpdatePolicySupplierDealCode_v1")]
		public int spDesktopDataAdmin_UpdatePolicySupplierDealCode_v1(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicySupplierDealCodeId", DbType="Int")] System.Nullable<int> policySupplierDealCodeId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierCode", DbType="NVarChar(50)")] string supplierCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicySupplierDealCodeValue", DbType="NVarChar(50)")] string policySupplierDealCodeValue, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicySupplierDealCodeDescription", DbType="NVarChar(50)")] string policySupplierDealCodeDescription, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GDSCode", DbType="VarChar(4)")] string gDSCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicySupplierDealCodeTypeId", DbType="Int")] System.Nullable<int> policySupplierDealCodeTypeId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyGroupId", DbType="Int")] System.Nullable<int> policyGroupId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledFlag", DbType="Bit")] System.Nullable<bool> enabledFlag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledDate", DbType="DateTime")] System.Nullable<System.DateTime> enabledDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpiryDate", DbType="DateTime")] System.Nullable<System.DateTime> expiryDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyLocationId", DbType="Int")] System.Nullable<int> policyLocationId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelIndicator", DbType="VarChar(1)")] string travelIndicator, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TourCodeTypeId", DbType="Int")] System.Nullable<int> tourCodeTypeId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Endorsement", DbType="NVarChar(120)")] string endorsement, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndorsementOverride", DbType="NVarChar(120)")] string endorsementOverride, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OSIFlag", DbType="Bit")] System.Nullable<bool> oSIFlag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicySupplierDealCodeOSIXML", DbType="Xml")] System.Xml.Linq.XElement policySupplierDealCodeOSIXML, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policySupplierDealCodeId, supplierCode, policySupplierDealCodeValue, policySupplierDealCodeDescription, gDSCode, productId, policySupplierDealCodeTypeId, policyGroupId, enabledFlag, enabledDate, expiryDate, policyLocationId, travelIndicator, tourCodeTypeId, endorsement, endorsementOverride, oSIFlag, policySupplierDealCodeOSIXML, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PolicySupplierDealCodeOSI")]
	public partial class PolicySupplierDealCodeOSI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PolicySupplierDealCodeOSIId;
		
		private System.Nullable<int> _PolicySupplierDealCodeId;
		
		private string _PolicySupplierDealCodeOSIDescription;
		
		private System.Nullable<int> _PolicySupplierDealCodeOSISequenceNumber;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private System.Nullable<int> _VersionNumber;
		
		private EntityRef<PolicySupplierDealCode> _PolicySupplierDealCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPolicySupplierDealCodeOSIIdChanging(int value);
    partial void OnPolicySupplierDealCodeOSIIdChanged();
    partial void OnPolicySupplierDealCodeIdChanging(System.Nullable<int> value);
    partial void OnPolicySupplierDealCodeIdChanged();
    partial void OnPolicySupplierDealCodeOSIDescriptionChanging(string value);
    partial void OnPolicySupplierDealCodeOSIDescriptionChanged();
    partial void OnPolicySupplierDealCodeOSISequenceNumberChanging(System.Nullable<int> value);
    partial void OnPolicySupplierDealCodeOSISequenceNumberChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(System.Nullable<int> value);
    partial void OnVersionNumberChanged();
    #endregion
		
		public PolicySupplierDealCodeOSI()
		{
			this._PolicySupplierDealCode = default(EntityRef<PolicySupplierDealCode>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicySupplierDealCodeOSIId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PolicySupplierDealCodeOSIId
		{
			get
			{
				return this._PolicySupplierDealCodeOSIId;
			}
			set
			{
				if ((this._PolicySupplierDealCodeOSIId != value))
				{
					this.OnPolicySupplierDealCodeOSIIdChanging(value);
					this.SendPropertyChanging();
					this._PolicySupplierDealCodeOSIId = value;
					this.SendPropertyChanged("PolicySupplierDealCodeOSIId");
					this.OnPolicySupplierDealCodeOSIIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicySupplierDealCodeId", DbType="Int")]
		public System.Nullable<int> PolicySupplierDealCodeId
		{
			get
			{
				return this._PolicySupplierDealCodeId;
			}
			set
			{
				if ((this._PolicySupplierDealCodeId != value))
				{
					if (this._PolicySupplierDealCode.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPolicySupplierDealCodeIdChanging(value);
					this.SendPropertyChanging();
					this._PolicySupplierDealCodeId = value;
					this.SendPropertyChanged("PolicySupplierDealCodeId");
					this.OnPolicySupplierDealCodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicySupplierDealCodeOSIDescription", DbType="NVarChar(80)")]
		public string PolicySupplierDealCodeOSIDescription
		{
			get
			{
				return this._PolicySupplierDealCodeOSIDescription;
			}
			set
			{
				if ((this._PolicySupplierDealCodeOSIDescription != value))
				{
					this.OnPolicySupplierDealCodeOSIDescriptionChanging(value);
					this.SendPropertyChanging();
					this._PolicySupplierDealCodeOSIDescription = value;
					this.SendPropertyChanged("PolicySupplierDealCodeOSIDescription");
					this.OnPolicySupplierDealCodeOSIDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicySupplierDealCodeOSISequenceNumber", DbType="Int")]
		public System.Nullable<int> PolicySupplierDealCodeOSISequenceNumber
		{
			get
			{
				return this._PolicySupplierDealCodeOSISequenceNumber;
			}
			set
			{
				if ((this._PolicySupplierDealCodeOSISequenceNumber != value))
				{
					this.OnPolicySupplierDealCodeOSISequenceNumberChanging(value);
					this.SendPropertyChanging();
					this._PolicySupplierDealCodeOSISequenceNumber = value;
					this.SendPropertyChanged("PolicySupplierDealCodeOSISequenceNumber");
					this.OnPolicySupplierDealCodeOSISequenceNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int")]
		public System.Nullable<int> VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PolicySupplierDealCode_PolicySupplierDealCodeOSI", Storage="_PolicySupplierDealCode", ThisKey="PolicySupplierDealCodeId", OtherKey="PolicySupplierDealCodeId", IsForeignKey=true)]
		public PolicySupplierDealCode PolicySupplierDealCode
		{
			get
			{
				return this._PolicySupplierDealCode.Entity;
			}
			set
			{
				PolicySupplierDealCode previousValue = this._PolicySupplierDealCode.Entity;
				if (((previousValue != value) 
							|| (this._PolicySupplierDealCode.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PolicySupplierDealCode.Entity = null;
						previousValue.PolicySupplierDealCodeOSIs.Remove(this);
					}
					this._PolicySupplierDealCode.Entity = value;
					if ((value != null))
					{
						value.PolicySupplierDealCodeOSIs.Add(this);
						this._PolicySupplierDealCodeId = value.PolicySupplierDealCodeId;
					}
					else
					{
						this._PolicySupplierDealCodeId = default(Nullable<int>);
					}
					this.SendPropertyChanged("PolicySupplierDealCode");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PolicySupplierDealCode")]
	public partial class PolicySupplierDealCode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PolicySupplierDealCodeId;
		
		private string _SupplierCode;
		
		private string _PolicySupplierDealCodeValue;
		
		private string _PolicySupplierDealCodeDescription;
		
		private string _GDSCode;
		
		private int _ProductId;
		
		private int _PolicySupplierDealCodeTypeId;
		
		private int _PolicyGroupId;
		
		private System.Nullable<bool> _EnabledFlag;
		
		private System.Nullable<System.DateTime> _ExpiryDate;
		
		private System.Nullable<System.DateTime> _EnabledDate;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private int _VersionNumber;
		
		private System.Nullable<int> _PolicyLocationId;
		
		private string _TravelIndicator;
		
		private System.Nullable<int> _TourCodeTypeId;
		
		private string _Endorsement;
		
		private string _EndorsementOverride;
		
		private System.Nullable<bool> _OSIFlag;
		
		private EntitySet<PolicySupplierDealCodeOSI> _PolicySupplierDealCodeOSIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPolicySupplierDealCodeIdChanging(int value);
    partial void OnPolicySupplierDealCodeIdChanged();
    partial void OnSupplierCodeChanging(string value);
    partial void OnSupplierCodeChanged();
    partial void OnPolicySupplierDealCodeValueChanging(string value);
    partial void OnPolicySupplierDealCodeValueChanged();
    partial void OnPolicySupplierDealCodeDescriptionChanging(string value);
    partial void OnPolicySupplierDealCodeDescriptionChanged();
    partial void OnGDSCodeChanging(string value);
    partial void OnGDSCodeChanged();
    partial void OnProductIdChanging(int value);
    partial void OnProductIdChanged();
    partial void OnPolicySupplierDealCodeTypeIdChanging(int value);
    partial void OnPolicySupplierDealCodeTypeIdChanged();
    partial void OnPolicyGroupIdChanging(int value);
    partial void OnPolicyGroupIdChanged();
    partial void OnEnabledFlagChanging(System.Nullable<bool> value);
    partial void OnEnabledFlagChanged();
    partial void OnExpiryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpiryDateChanged();
    partial void OnEnabledDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnabledDateChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(int value);
    partial void OnVersionNumberChanged();
    partial void OnPolicyLocationIdChanging(System.Nullable<int> value);
    partial void OnPolicyLocationIdChanged();
    partial void OnTravelIndicatorChanging(string value);
    partial void OnTravelIndicatorChanged();
    partial void OnTourCodeTypeIdChanging(System.Nullable<int> value);
    partial void OnTourCodeTypeIdChanged();
    partial void OnEndorsementChanging(string value);
    partial void OnEndorsementChanged();
    partial void OnEndorsementOverrideChanging(string value);
    partial void OnEndorsementOverrideChanged();
    partial void OnOSIFlagChanging(System.Nullable<bool> value);
    partial void OnOSIFlagChanged();
    #endregion
		
		public PolicySupplierDealCode()
		{
			this._PolicySupplierDealCodeOSIs = new EntitySet<PolicySupplierDealCodeOSI>(new Action<PolicySupplierDealCodeOSI>(this.attach_PolicySupplierDealCodeOSIs), new Action<PolicySupplierDealCodeOSI>(this.detach_PolicySupplierDealCodeOSIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicySupplierDealCodeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PolicySupplierDealCodeId
		{
			get
			{
				return this._PolicySupplierDealCodeId;
			}
			set
			{
				if ((this._PolicySupplierDealCodeId != value))
				{
					this.OnPolicySupplierDealCodeIdChanging(value);
					this.SendPropertyChanging();
					this._PolicySupplierDealCodeId = value;
					this.SendPropertyChanged("PolicySupplierDealCodeId");
					this.OnPolicySupplierDealCodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SupplierCode
		{
			get
			{
				return this._SupplierCode;
			}
			set
			{
				if ((this._SupplierCode != value))
				{
					this.OnSupplierCodeChanging(value);
					this.SendPropertyChanging();
					this._SupplierCode = value;
					this.SendPropertyChanged("SupplierCode");
					this.OnSupplierCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicySupplierDealCodeValue", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PolicySupplierDealCodeValue
		{
			get
			{
				return this._PolicySupplierDealCodeValue;
			}
			set
			{
				if ((this._PolicySupplierDealCodeValue != value))
				{
					this.OnPolicySupplierDealCodeValueChanging(value);
					this.SendPropertyChanging();
					this._PolicySupplierDealCodeValue = value;
					this.SendPropertyChanged("PolicySupplierDealCodeValue");
					this.OnPolicySupplierDealCodeValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicySupplierDealCodeDescription", DbType="NVarChar(100)")]
		public string PolicySupplierDealCodeDescription
		{
			get
			{
				return this._PolicySupplierDealCodeDescription;
			}
			set
			{
				if ((this._PolicySupplierDealCodeDescription != value))
				{
					this.OnPolicySupplierDealCodeDescriptionChanging(value);
					this.SendPropertyChanging();
					this._PolicySupplierDealCodeDescription = value;
					this.SendPropertyChanged("PolicySupplierDealCodeDescription");
					this.OnPolicySupplierDealCodeDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GDSCode", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string GDSCode
		{
			get
			{
				return this._GDSCode;
			}
			set
			{
				if ((this._GDSCode != value))
				{
					this.OnGDSCodeChanging(value);
					this.SendPropertyChanging();
					this._GDSCode = value;
					this.SendPropertyChanged("GDSCode");
					this.OnGDSCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int NOT NULL")]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicySupplierDealCodeTypeId", DbType="Int NOT NULL")]
		public int PolicySupplierDealCodeTypeId
		{
			get
			{
				return this._PolicySupplierDealCodeTypeId;
			}
			set
			{
				if ((this._PolicySupplierDealCodeTypeId != value))
				{
					this.OnPolicySupplierDealCodeTypeIdChanging(value);
					this.SendPropertyChanging();
					this._PolicySupplierDealCodeTypeId = value;
					this.SendPropertyChanged("PolicySupplierDealCodeTypeId");
					this.OnPolicySupplierDealCodeTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyGroupId", DbType="Int NOT NULL")]
		public int PolicyGroupId
		{
			get
			{
				return this._PolicyGroupId;
			}
			set
			{
				if ((this._PolicyGroupId != value))
				{
					this.OnPolicyGroupIdChanging(value);
					this.SendPropertyChanging();
					this._PolicyGroupId = value;
					this.SendPropertyChanged("PolicyGroupId");
					this.OnPolicyGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnabledFlag", DbType="Bit")]
		public System.Nullable<bool> EnabledFlag
		{
			get
			{
				return this._EnabledFlag;
			}
			set
			{
				if ((this._EnabledFlag != value))
				{
					this.OnEnabledFlagChanging(value);
					this.SendPropertyChanging();
					this._EnabledFlag = value;
					this.SendPropertyChanged("EnabledFlag");
					this.OnEnabledFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpiryDate
		{
			get
			{
				return this._ExpiryDate;
			}
			set
			{
				if ((this._ExpiryDate != value))
				{
					this.OnExpiryDateChanging(value);
					this.SendPropertyChanging();
					this._ExpiryDate = value;
					this.SendPropertyChanged("ExpiryDate");
					this.OnExpiryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnabledDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EnabledDate
		{
			get
			{
				return this._EnabledDate;
			}
			set
			{
				if ((this._EnabledDate != value))
				{
					this.OnEnabledDateChanging(value);
					this.SendPropertyChanging();
					this._EnabledDate = value;
					this.SendPropertyChanged("EnabledDate");
					this.OnEnabledDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int NOT NULL")]
		public int VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyLocationId", DbType="Int")]
		public System.Nullable<int> PolicyLocationId
		{
			get
			{
				return this._PolicyLocationId;
			}
			set
			{
				if ((this._PolicyLocationId != value))
				{
					this.OnPolicyLocationIdChanging(value);
					this.SendPropertyChanging();
					this._PolicyLocationId = value;
					this.SendPropertyChanged("PolicyLocationId");
					this.OnPolicyLocationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelIndicator", DbType="VarChar(1)")]
		public string TravelIndicator
		{
			get
			{
				return this._TravelIndicator;
			}
			set
			{
				if ((this._TravelIndicator != value))
				{
					this.OnTravelIndicatorChanging(value);
					this.SendPropertyChanging();
					this._TravelIndicator = value;
					this.SendPropertyChanged("TravelIndicator");
					this.OnTravelIndicatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TourCodeTypeId", DbType="Int")]
		public System.Nullable<int> TourCodeTypeId
		{
			get
			{
				return this._TourCodeTypeId;
			}
			set
			{
				if ((this._TourCodeTypeId != value))
				{
					this.OnTourCodeTypeIdChanging(value);
					this.SendPropertyChanging();
					this._TourCodeTypeId = value;
					this.SendPropertyChanged("TourCodeTypeId");
					this.OnTourCodeTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endorsement", DbType="NVarChar(120)")]
		public string Endorsement
		{
			get
			{
				return this._Endorsement;
			}
			set
			{
				if ((this._Endorsement != value))
				{
					this.OnEndorsementChanging(value);
					this.SendPropertyChanging();
					this._Endorsement = value;
					this.SendPropertyChanged("Endorsement");
					this.OnEndorsementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndorsementOverride", DbType="NVarChar(120)")]
		public string EndorsementOverride
		{
			get
			{
				return this._EndorsementOverride;
			}
			set
			{
				if ((this._EndorsementOverride != value))
				{
					this.OnEndorsementOverrideChanging(value);
					this.SendPropertyChanging();
					this._EndorsementOverride = value;
					this.SendPropertyChanged("EndorsementOverride");
					this.OnEndorsementOverrideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSIFlag", DbType="Bit")]
		public System.Nullable<bool> OSIFlag
		{
			get
			{
				return this._OSIFlag;
			}
			set
			{
				if ((this._OSIFlag != value))
				{
					this.OnOSIFlagChanging(value);
					this.SendPropertyChanging();
					this._OSIFlag = value;
					this.SendPropertyChanged("OSIFlag");
					this.OnOSIFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PolicySupplierDealCode_PolicySupplierDealCodeOSI", Storage="_PolicySupplierDealCodeOSIs", ThisKey="PolicySupplierDealCodeId", OtherKey="PolicySupplierDealCodeId")]
		public EntitySet<PolicySupplierDealCodeOSI> PolicySupplierDealCodeOSIs
		{
			get
			{
				return this._PolicySupplierDealCodeOSIs;
			}
			set
			{
				this._PolicySupplierDealCodeOSIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PolicySupplierDealCodeOSIs(PolicySupplierDealCodeOSI entity)
		{
			this.SendPropertyChanging();
			entity.PolicySupplierDealCode = this;
		}
		
		private void detach_PolicySupplierDealCodeOSIs(PolicySupplierDealCodeOSI entity)
		{
			this.SendPropertyChanging();
			entity.PolicySupplierDealCode = null;
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPolicySupplierDealCodes_v1Result
	{
		
		private int _PolicySupplierDealCodeId;
		
		private string _PolicySupplierDealCodeValue;
		
		private string _PolicySupplierDealCodeTypeDescription;
		
		private string _GDSName;
		
		private string _SupplierName;
		
		private string _PolicyLocationName;
		
		private System.Nullable<int> _RecordCount;
		
		public spDesktopDataAdmin_SelectPolicySupplierDealCodes_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicySupplierDealCodeId", DbType="Int NOT NULL")]
		public int PolicySupplierDealCodeId
		{
			get
			{
				return this._PolicySupplierDealCodeId;
			}
			set
			{
				if ((this._PolicySupplierDealCodeId != value))
				{
					this._PolicySupplierDealCodeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicySupplierDealCodeValue", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PolicySupplierDealCodeValue
		{
			get
			{
				return this._PolicySupplierDealCodeValue;
			}
			set
			{
				if ((this._PolicySupplierDealCodeValue != value))
				{
					this._PolicySupplierDealCodeValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicySupplierDealCodeTypeDescription", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PolicySupplierDealCodeTypeDescription
		{
			get
			{
				return this._PolicySupplierDealCodeTypeDescription;
			}
			set
			{
				if ((this._PolicySupplierDealCodeTypeDescription != value))
				{
					this._PolicySupplierDealCodeTypeDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GDSName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GDSName
		{
			get
			{
				return this._GDSName;
			}
			set
			{
				if ((this._GDSName != value))
				{
					this._GDSName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string SupplierName
		{
			get
			{
				return this._SupplierName;
			}
			set
			{
				if ((this._SupplierName != value))
				{
					this._SupplierName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyLocationName", DbType="NVarChar(100)")]
		public string PolicyLocationName
		{
			get
			{
				return this._PolicyLocationName;
			}
			set
			{
				if ((this._PolicyLocationName != value))
				{
					this._PolicyLocationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCount", DbType="Int")]
		public System.Nullable<int> RecordCount
		{
			get
			{
				return this._RecordCount;
			}
			set
			{
				if ((this._RecordCount != value))
				{
					this._RecordCount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
