#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Desktop_Local_v1713")]
	public partial class PolicyLocationDC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPolicyLocation(PolicyLocation instance);
    partial void UpdatePolicyLocation(PolicyLocation instance);
    partial void DeletePolicyLocation(PolicyLocation instance);
    #endregion
		
		public PolicyLocationDC() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Desktop_Local_v1713ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyLocationDC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyLocationDC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyLocationDC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyLocationDC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PolicyLocation> PolicyLocations
		{
			get
			{
				return this.GetTable<PolicyLocation>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_InsertPolicyLocation_v1")]
		public int spDesktopDataAdmin_InsertPolicyLocation_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyLocationName", DbType="NVarChar(100)")] string policyLocationName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GlobalFlag", DbType="Bit")] System.Nullable<bool> globalFlag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GlobalRegionCode", DbType="VarChar(5)")] string globalRegionCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GlobalSubRegionCode", DbType="VarChar(5)")] string globalSubRegionCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountryCode", DbType="VarChar(2)")] string countryCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityCode", DbType="NVarChar(5)")] string cityCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelPortCode", DbType="NVarChar(50)")] string travelPortCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelPortTypeId", DbType="Int")] System.Nullable<int> travelPortTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyLocationName, globalFlag, globalRegionCode, globalSubRegionCode, countryCode, cityCode, travelPortCode, travelPortTypeId, adminUserGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_UpdatePolicyLocation_v1")]
		public int spDesktopDataAdmin_UpdatePolicyLocation_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyLocationId", DbType="Int")] System.Nullable<int> policyLocationId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyLocationName", DbType="NVarChar(100)")] string policyLocationName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GlobalFlag", DbType="Bit")] System.Nullable<bool> globalFlag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GlobalRegionCode", DbType="VarChar(5)")] string globalRegionCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GlobalSubRegionCode", DbType="VarChar(5)")] string globalSubRegionCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountryCode", DbType="VarChar(2)")] string countryCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityCode", DbType="NVarChar(5)")] string cityCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelPortCode", DbType="NVarChar(50)")] string travelPortCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelPortTypeId", DbType="Int")] System.Nullable<int> travelPortTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyLocationId, policyLocationName, globalFlag, globalRegionCode, globalSubRegionCode, countryCode, cityCode, travelPortCode, travelPortTypeId, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fnDesktopDataAdmin_SelectPolicyLocationLocations_v1", IsComposable=true)]
		public IQueryable<fnDesktopDataAdmin_SelectPolicyLocationLocations_v1Result> fnDesktopDataAdmin_SelectPolicyLocationLocations_v1()
		{
			return this.CreateMethodCallQuery<fnDesktopDataAdmin_SelectPolicyLocationLocations_v1Result>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_DeletePolicyLocation_v1")]
		public int spDesktopDataAdmin_DeletePolicyLocation_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyLocationId", DbType="Int")] System.Nullable<int> policyLocationId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyLocationId, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPolicyLocations_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPolicyLocations_v1Result> spDesktopDataAdmin_SelectPolicyLocations_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filter", DbType="VarChar(25)")] string filter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortField", DbType="VarChar(50)")] string sortField, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), filter, sortField, sortOrder, pageNumber, adminUserGuid);
			return ((ISingleResult<spDesktopDataAdmin_SelectPolicyLocations_v1Result>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PolicyLocation")]
	public partial class PolicyLocation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PolicyLocationId;
		
		private string _PolicyLocationName;
		
		private bool _GlobalFlag;
		
		private string _GlobalRegionCode;
		
		private string _GlobalSubRegionCode;
		
		private string _CountryCode;
		
		private string _CityCode;
		
		private string _TravelPortCode;
		
		private System.Nullable<int> _TravelPortTypeId;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private System.Nullable<int> _VersionNumber;
		
		private EntityRef<PolicyLocation> _PolicyLocation2;
		
		private EntityRef<PolicyLocation> _PolicyLocation1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPolicyLocationIdChanging(int value);
    partial void OnPolicyLocationIdChanged();
    partial void OnPolicyLocationNameChanging(string value);
    partial void OnPolicyLocationNameChanged();
    partial void OnGlobalFlagChanging(bool value);
    partial void OnGlobalFlagChanged();
    partial void OnGlobalRegionCodeChanging(string value);
    partial void OnGlobalRegionCodeChanged();
    partial void OnGlobalSubRegionCodeChanging(string value);
    partial void OnGlobalSubRegionCodeChanged();
    partial void OnCountryCodeChanging(string value);
    partial void OnCountryCodeChanged();
    partial void OnCityCodeChanging(string value);
    partial void OnCityCodeChanged();
    partial void OnTravelPortCodeChanging(string value);
    partial void OnTravelPortCodeChanged();
    partial void OnTravelPortTypeIdChanging(System.Nullable<int> value);
    partial void OnTravelPortTypeIdChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(System.Nullable<int> value);
    partial void OnVersionNumberChanged();
    #endregion
		
		public PolicyLocation()
		{
			this._PolicyLocation2 = default(EntityRef<PolicyLocation>);
			this._PolicyLocation1 = default(EntityRef<PolicyLocation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyLocationId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PolicyLocationId
		{
			get
			{
				return this._PolicyLocationId;
			}
			set
			{
				if ((this._PolicyLocationId != value))
				{
					if (this._PolicyLocation1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPolicyLocationIdChanging(value);
					this.SendPropertyChanging();
					this._PolicyLocationId = value;
					this.SendPropertyChanged("PolicyLocationId");
					this.OnPolicyLocationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyLocationName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PolicyLocationName
		{
			get
			{
				return this._PolicyLocationName;
			}
			set
			{
				if ((this._PolicyLocationName != value))
				{
					this.OnPolicyLocationNameChanging(value);
					this.SendPropertyChanging();
					this._PolicyLocationName = value;
					this.SendPropertyChanged("PolicyLocationName");
					this.OnPolicyLocationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlobalFlag", DbType="Bit NOT NULL")]
		public bool GlobalFlag
		{
			get
			{
				return this._GlobalFlag;
			}
			set
			{
				if ((this._GlobalFlag != value))
				{
					this.OnGlobalFlagChanging(value);
					this.SendPropertyChanging();
					this._GlobalFlag = value;
					this.SendPropertyChanged("GlobalFlag");
					this.OnGlobalFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlobalRegionCode", DbType="VarChar(5)")]
		public string GlobalRegionCode
		{
			get
			{
				return this._GlobalRegionCode;
			}
			set
			{
				if ((this._GlobalRegionCode != value))
				{
					this.OnGlobalRegionCodeChanging(value);
					this.SendPropertyChanging();
					this._GlobalRegionCode = value;
					this.SendPropertyChanged("GlobalRegionCode");
					this.OnGlobalRegionCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlobalSubRegionCode", DbType="VarChar(5)")]
		public string GlobalSubRegionCode
		{
			get
			{
				return this._GlobalSubRegionCode;
			}
			set
			{
				if ((this._GlobalSubRegionCode != value))
				{
					this.OnGlobalSubRegionCodeChanging(value);
					this.SendPropertyChanging();
					this._GlobalSubRegionCode = value;
					this.SendPropertyChanged("GlobalSubRegionCode");
					this.OnGlobalSubRegionCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryCode", DbType="VarChar(2)")]
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this.OnCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._CountryCode = value;
					this.SendPropertyChanged("CountryCode");
					this.OnCountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityCode", DbType="NVarChar(5)")]
		public string CityCode
		{
			get
			{
				return this._CityCode;
			}
			set
			{
				if ((this._CityCode != value))
				{
					this.OnCityCodeChanging(value);
					this.SendPropertyChanging();
					this._CityCode = value;
					this.SendPropertyChanged("CityCode");
					this.OnCityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelPortCode", DbType="NVarChar(50)")]
		public string TravelPortCode
		{
			get
			{
				return this._TravelPortCode;
			}
			set
			{
				if ((this._TravelPortCode != value))
				{
					this.OnTravelPortCodeChanging(value);
					this.SendPropertyChanging();
					this._TravelPortCode = value;
					this.SendPropertyChanged("TravelPortCode");
					this.OnTravelPortCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelPortTypeId", DbType="Int")]
		public System.Nullable<int> TravelPortTypeId
		{
			get
			{
				return this._TravelPortTypeId;
			}
			set
			{
				if ((this._TravelPortTypeId != value))
				{
					this.OnTravelPortTypeIdChanging(value);
					this.SendPropertyChanging();
					this._TravelPortTypeId = value;
					this.SendPropertyChanged("TravelPortTypeId");
					this.OnTravelPortTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int")]
		public System.Nullable<int> VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PolicyLocation_PolicyLocation", Storage="_PolicyLocation2", ThisKey="PolicyLocationId", OtherKey="PolicyLocationId", IsUnique=true, IsForeignKey=false)]
		public PolicyLocation PolicyLocation2
		{
			get
			{
				return this._PolicyLocation2.Entity;
			}
			set
			{
				PolicyLocation previousValue = this._PolicyLocation2.Entity;
				if (((previousValue != value) 
							|| (this._PolicyLocation2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PolicyLocation2.Entity = null;
						previousValue.PolicyLocation1 = null;
					}
					this._PolicyLocation2.Entity = value;
					if ((value != null))
					{
						value.PolicyLocation1 = this;
					}
					this.SendPropertyChanged("PolicyLocation2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PolicyLocation_PolicyLocation", Storage="_PolicyLocation1", ThisKey="PolicyLocationId", OtherKey="PolicyLocationId", IsForeignKey=true)]
		public PolicyLocation PolicyLocation1
		{
			get
			{
				return this._PolicyLocation1.Entity;
			}
			set
			{
				PolicyLocation previousValue = this._PolicyLocation1.Entity;
				if (((previousValue != value) 
							|| (this._PolicyLocation1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PolicyLocation1.Entity = null;
						previousValue.PolicyLocation2 = null;
					}
					this._PolicyLocation1.Entity = value;
					if ((value != null))
					{
						value.PolicyLocation2 = this;
						this._PolicyLocationId = value.PolicyLocationId;
					}
					else
					{
						this._PolicyLocationId = default(int);
					}
					this.SendPropertyChanged("PolicyLocation1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class fnDesktopDataAdmin_SelectPolicyLocationLocations_v1Result
	{
		
		private string _Code;
		
		private string _Name;
		
		private string _Parent;
		
		private string _CodeType;
		
		public fnDesktopDataAdmin_SelectPolicyLocationLocations_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this._Parent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeType", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CodeType
		{
			get
			{
				return this._CodeType;
			}
			set
			{
				if ((this._CodeType != value))
				{
					this._CodeType = value;
				}
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPolicyLocations_v1Result
	{
		
		private System.Nullable<int> _PolicyLocationId;
		
		private string _PolicyLocationName;
		
		private string _PolicyLocationValue;
		
		private System.Nullable<int> _RecordCount;
		
		public spDesktopDataAdmin_SelectPolicyLocations_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyLocationId", DbType="Int")]
		public System.Nullable<int> PolicyLocationId
		{
			get
			{
				return this._PolicyLocationId;
			}
			set
			{
				if ((this._PolicyLocationId != value))
				{
					this._PolicyLocationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyLocationName", DbType="NVarChar(100)")]
		public string PolicyLocationName
		{
			get
			{
				return this._PolicyLocationName;
			}
			set
			{
				if ((this._PolicyLocationName != value))
				{
					this._PolicyLocationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyLocationValue", DbType="NVarChar(100)")]
		public string PolicyLocationValue
		{
			get
			{
				return this._PolicyLocationValue;
			}
			set
			{
				if ((this._PolicyLocationValue != value))
				{
					this._PolicyLocationValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCount", DbType="Int")]
		public System.Nullable<int> RecordCount
		{
			get
			{
				return this._RecordCount;
			}
			set
			{
				if ((this._RecordCount != value))
				{
					this._RecordCount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
