#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Desktop_Local_v1851")]
	public partial class PolicyCarVendorGroupItemDC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPolicyCarVendorGroupItem(PolicyCarVendorGroupItem instance);
    partial void UpdatePolicyCarVendorGroupItem(PolicyCarVendorGroupItem instance);
    partial void DeletePolicyCarVendorGroupItem(PolicyCarVendorGroupItem instance);
    #endregion
		
		public PolicyCarVendorGroupItemDC() : 
				base(global::CWTDesktopDatabase.Properties.Settings.Default.Desktop_Local_v1851ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyCarVendorGroupItemDC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyCarVendorGroupItemDC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyCarVendorGroupItemDC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyCarVendorGroupItemDC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PolicyCarVendorGroupItem> PolicyCarVendorGroupItems
		{
			get
			{
				return this.GetTable<PolicyCarVendorGroupItem>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_InsertPolicyCarVendorGroupItem_v1")]
		public int spDesktopDataAdmin_InsertPolicyCarVendorGroupItem_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyGroupId", DbType="Int")] System.Nullable<int> policyGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyLocationId", DbType="Int")] System.Nullable<int> policyLocationId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierCode", DbType="NVarChar(50)")] string supplierCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyCarStatusId", DbType="Int")] System.Nullable<int> policyCarStatusId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledFlag", DbType="Bit")] System.Nullable<bool> enabledFlag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledDate", DbType="DateTime")] System.Nullable<System.DateTime> enabledDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpiryDate", DbType="DateTime")] System.Nullable<System.DateTime> expiryDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelDateValidFrom", DbType="DateTime")] System.Nullable<System.DateTime> travelDateValidFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelDateValidTo", DbType="DateTime")] System.Nullable<System.DateTime> travelDateValidTo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyGroupId, policyLocationId, supplierCode, productId, policyCarStatusId, enabledFlag, enabledDate, expiryDate, travelDateValidFrom, travelDateValidTo, adminUserGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_UpdatePolicyCarVendorGroupItem_v1")]
		public int spDesktopDataAdmin_UpdatePolicyCarVendorGroupItem_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyCarVendorGroupItemId", DbType="Int")] System.Nullable<int> policyCarVendorGroupItemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyGroupId", DbType="Int")] System.Nullable<int> policyGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyLocationId", DbType="Int")] System.Nullable<int> policyLocationId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierCode", DbType="NVarChar(50)")] string supplierCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyCarStatusId", DbType="Int")] System.Nullable<int> policyCarStatusId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledFlag", DbType="Bit")] System.Nullable<bool> enabledFlag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledDate", DbType="DateTime")] System.Nullable<System.DateTime> enabledDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpiryDate", DbType="DateTime")] System.Nullable<System.DateTime> expiryDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelDateValidFrom", DbType="DateTime")] System.Nullable<System.DateTime> travelDateValidFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelDateValidTo", DbType="DateTime")] System.Nullable<System.DateTime> travelDateValidTo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyCarVendorGroupItemId, policyGroupId, policyLocationId, supplierCode, productId, policyCarStatusId, enabledFlag, enabledDate, expiryDate, travelDateValidFrom, travelDateValidTo, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_DeletePolicyCarVendorGroupItem_v1")]
		public int spDesktopDataAdmin_DeletePolicyCarVendorGroupItem_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyCarVendorGroupItemId", DbType="Int")] System.Nullable<int> policyCarVendorGroupItemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyCarVendorGroupItemId, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPolicyCarVendorGroupItems_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPolicyCarVendorGroupItems_v1Result> spDesktopDataAdmin_SelectPolicyCarVendorGroupItems_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyGroupID", DbType="Int")] System.Nullable<int> policyGroupID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SystemUserGuid", DbType="VarChar(13)")] string systemUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortField", DbType="VarChar(50)")] string sortField, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Bit")] System.Nullable<bool> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyGroupID, systemUserGuid, sortField, sortOrder, pageNumber);
			return ((ISingleResult<spDesktopDataAdmin_SelectPolicyCarVendorGroupItems_v1Result>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PolicyCarVendorGroupItem")]
	public partial class PolicyCarVendorGroupItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PolicyGroupId;
		
		private int _PolicyCarVendorGroupItemId;
		
		private int _PolicyLocationId;
		
		private string _SupplierCode;
		
		private int _ProductId;
		
		private System.Nullable<int> _PolicyCarStatusId;
		
		private bool _EnabledFlag;
		
		private int _SequenceNumber;
		
		private System.Nullable<System.DateTime> _EnabledDate;
		
		private System.Nullable<System.DateTime> _ExpiryDate;
		
		private System.Nullable<System.DateTime> _TravelDateValidFrom;
		
		private System.Nullable<System.DateTime> _TravelDateValidTo;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private System.Nullable<int> _VersionNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPolicyGroupIdChanging(int value);
    partial void OnPolicyGroupIdChanged();
    partial void OnPolicyCarVendorGroupItemIdChanging(int value);
    partial void OnPolicyCarVendorGroupItemIdChanged();
    partial void OnPolicyLocationIdChanging(int value);
    partial void OnPolicyLocationIdChanged();
    partial void OnSupplierCodeChanging(string value);
    partial void OnSupplierCodeChanged();
    partial void OnProductIdChanging(int value);
    partial void OnProductIdChanged();
    partial void OnPolicyCarStatusIdChanging(System.Nullable<int> value);
    partial void OnPolicyCarStatusIdChanged();
    partial void OnEnabledFlagChanging(bool value);
    partial void OnEnabledFlagChanged();
    partial void OnSequenceNumberChanging(int value);
    partial void OnSequenceNumberChanged();
    partial void OnEnabledDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnabledDateChanged();
    partial void OnExpiryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpiryDateChanged();
    partial void OnTravelDateValidFromChanging(System.Nullable<System.DateTime> value);
    partial void OnTravelDateValidFromChanged();
    partial void OnTravelDateValidToChanging(System.Nullable<System.DateTime> value);
    partial void OnTravelDateValidToChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(System.Nullable<int> value);
    partial void OnVersionNumberChanged();
    #endregion
		
		public PolicyCarVendorGroupItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyGroupId", DbType="Int NOT NULL")]
		public int PolicyGroupId
		{
			get
			{
				return this._PolicyGroupId;
			}
			set
			{
				if ((this._PolicyGroupId != value))
				{
					this.OnPolicyGroupIdChanging(value);
					this.SendPropertyChanging();
					this._PolicyGroupId = value;
					this.SendPropertyChanged("PolicyGroupId");
					this.OnPolicyGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyCarVendorGroupItemId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PolicyCarVendorGroupItemId
		{
			get
			{
				return this._PolicyCarVendorGroupItemId;
			}
			set
			{
				if ((this._PolicyCarVendorGroupItemId != value))
				{
					this.OnPolicyCarVendorGroupItemIdChanging(value);
					this.SendPropertyChanging();
					this._PolicyCarVendorGroupItemId = value;
					this.SendPropertyChanged("PolicyCarVendorGroupItemId");
					this.OnPolicyCarVendorGroupItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyLocationId", DbType="Int NOT NULL")]
		public int PolicyLocationId
		{
			get
			{
				return this._PolicyLocationId;
			}
			set
			{
				if ((this._PolicyLocationId != value))
				{
					this.OnPolicyLocationIdChanging(value);
					this.SendPropertyChanging();
					this._PolicyLocationId = value;
					this.SendPropertyChanged("PolicyLocationId");
					this.OnPolicyLocationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SupplierCode
		{
			get
			{
				return this._SupplierCode;
			}
			set
			{
				if ((this._SupplierCode != value))
				{
					this.OnSupplierCodeChanging(value);
					this.SendPropertyChanging();
					this._SupplierCode = value;
					this.SendPropertyChanged("SupplierCode");
					this.OnSupplierCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int NOT NULL")]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyCarStatusId", DbType="Int")]
		public System.Nullable<int> PolicyCarStatusId
		{
			get
			{
				return this._PolicyCarStatusId;
			}
			set
			{
				if ((this._PolicyCarStatusId != value))
				{
					this.OnPolicyCarStatusIdChanging(value);
					this.SendPropertyChanging();
					this._PolicyCarStatusId = value;
					this.SendPropertyChanged("PolicyCarStatusId");
					this.OnPolicyCarStatusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnabledFlag", DbType="Bit NOT NULL")]
		public bool EnabledFlag
		{
			get
			{
				return this._EnabledFlag;
			}
			set
			{
				if ((this._EnabledFlag != value))
				{
					this.OnEnabledFlagChanging(value);
					this.SendPropertyChanging();
					this._EnabledFlag = value;
					this.SendPropertyChanged("EnabledFlag");
					this.OnEnabledFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SequenceNumber", DbType="Int NOT NULL")]
		public int SequenceNumber
		{
			get
			{
				return this._SequenceNumber;
			}
			set
			{
				if ((this._SequenceNumber != value))
				{
					this.OnSequenceNumberChanging(value);
					this.SendPropertyChanging();
					this._SequenceNumber = value;
					this.SendPropertyChanged("SequenceNumber");
					this.OnSequenceNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnabledDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EnabledDate
		{
			get
			{
				return this._EnabledDate;
			}
			set
			{
				if ((this._EnabledDate != value))
				{
					this.OnEnabledDateChanging(value);
					this.SendPropertyChanging();
					this._EnabledDate = value;
					this.SendPropertyChanged("EnabledDate");
					this.OnEnabledDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpiryDate
		{
			get
			{
				return this._ExpiryDate;
			}
			set
			{
				if ((this._ExpiryDate != value))
				{
					this.OnExpiryDateChanging(value);
					this.SendPropertyChanging();
					this._ExpiryDate = value;
					this.SendPropertyChanged("ExpiryDate");
					this.OnExpiryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelDateValidFrom", DbType="DateTime")]
		public System.Nullable<System.DateTime> TravelDateValidFrom
		{
			get
			{
				return this._TravelDateValidFrom;
			}
			set
			{
				if ((this._TravelDateValidFrom != value))
				{
					this.OnTravelDateValidFromChanging(value);
					this.SendPropertyChanging();
					this._TravelDateValidFrom = value;
					this.SendPropertyChanged("TravelDateValidFrom");
					this.OnTravelDateValidFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelDateValidTo", DbType="DateTime")]
		public System.Nullable<System.DateTime> TravelDateValidTo
		{
			get
			{
				return this._TravelDateValidTo;
			}
			set
			{
				if ((this._TravelDateValidTo != value))
				{
					this.OnTravelDateValidToChanging(value);
					this.SendPropertyChanging();
					this._TravelDateValidTo = value;
					this.SendPropertyChanged("TravelDateValidTo");
					this.OnTravelDateValidToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int")]
		public System.Nullable<int> VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPolicyCarVendorGroupItems_v1Result
	{
		
		private int _SequenceNumber;
		
		private System.Nullable<int> _PolicyGroupId;
		
		private string _PolicyLocationName;
		
		private int _PolicyCarVendorGroupItemId;
		
		private System.Nullable<System.DateTime> _EnabledDate;
		
		private string _SupplierName;
		
		private string _PolicyCarStatusDescription;
		
		private System.Nullable<int> _Advice;
		
		private System.Nullable<bool> _HasWriteAccess;
		
		private System.Nullable<int> _RecordCount;
		
		public spDesktopDataAdmin_SelectPolicyCarVendorGroupItems_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SequenceNumber", DbType="Int NOT NULL")]
		public int SequenceNumber
		{
			get
			{
				return this._SequenceNumber;
			}
			set
			{
				if ((this._SequenceNumber != value))
				{
					this._SequenceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyGroupId", DbType="Int")]
		public System.Nullable<int> PolicyGroupId
		{
			get
			{
				return this._PolicyGroupId;
			}
			set
			{
				if ((this._PolicyGroupId != value))
				{
					this._PolicyGroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyLocationName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PolicyLocationName
		{
			get
			{
				return this._PolicyLocationName;
			}
			set
			{
				if ((this._PolicyLocationName != value))
				{
					this._PolicyLocationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyCarVendorGroupItemId", DbType="Int NOT NULL")]
		public int PolicyCarVendorGroupItemId
		{
			get
			{
				return this._PolicyCarVendorGroupItemId;
			}
			set
			{
				if ((this._PolicyCarVendorGroupItemId != value))
				{
					this._PolicyCarVendorGroupItemId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnabledDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EnabledDate
		{
			get
			{
				return this._EnabledDate;
			}
			set
			{
				if ((this._EnabledDate != value))
				{
					this._EnabledDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string SupplierName
		{
			get
			{
				return this._SupplierName;
			}
			set
			{
				if ((this._SupplierName != value))
				{
					this._SupplierName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyCarStatusDescription", DbType="NVarChar(50)")]
		public string PolicyCarStatusDescription
		{
			get
			{
				return this._PolicyCarStatusDescription;
			}
			set
			{
				if ((this._PolicyCarStatusDescription != value))
				{
					this._PolicyCarStatusDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advice", DbType="Int")]
		public System.Nullable<int> Advice
		{
			get
			{
				return this._Advice;
			}
			set
			{
				if ((this._Advice != value))
				{
					this._Advice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasWriteAccess", DbType="Bit")]
		public System.Nullable<bool> HasWriteAccess
		{
			get
			{
				return this._HasWriteAccess;
			}
			set
			{
				if ((this._HasWriteAccess != value))
				{
					this._HasWriteAccess = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCount", DbType="Int")]
		public System.Nullable<int> RecordCount
		{
			get
			{
				return this._RecordCount;
			}
			set
			{
				if ((this._RecordCount != value))
				{
					this._RecordCount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
