<?xml version="1.0" encoding="utf-8"?><Database Name="Desktop_Local_v1851" Class="PolicyAirCabinGroupItemDC" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.11.90;Initial Catalog=Desktop_Local_v1851;Persist Security Info=True;User ID=cdoadmin" SettingsObjectName="CWTDesktopDatabase.Properties.Settings" SettingsPropertyName="Desktop_Local_v1851ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PolicyAirCabinGroupItem" Member="PolicyAirCabinGroupItems">
    <Type Name="PolicyAirCabinGroupItem">
      <Column Name="PolicyAirCabinGroupItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PolicyGroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AirlineCabinCode" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="FlightDurationAllowedMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlightDurationAllowedMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyRoutingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyProhibitedFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EnabledFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EnabledDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TravelDateValidFrom" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TravelDateValidTo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="LastUpdateTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdateUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FlightMileageAllowedMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlightMileageAllowedMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PolicyAirCabinGroupItem_PolicyAirCabinGroupItemLanguage" Member="PolicyAirCabinGroupItemLanguages" ThisKey="PolicyAirCabinGroupItemId" OtherKey="PolicyAirCabinGroupItemId" Type="PolicyAirCabinGroupItemLanguage" />
    </Type>
  </Table>
  <Table Name="dbo.PolicyAirCabinGroupItemLanguage" Member="PolicyAirCabinGroupItemLanguages">
    <Type Name="PolicyAirCabinGroupItemLanguage">
      <Column Name="PolicyAirCabinGroupItemId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LanguageCode" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AirCabinAdvice" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="LastUpdateTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdateUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PolicyAirCabinGroupItem_PolicyAirCabinGroupItemLanguage" Member="PolicyAirCabinGroupItem" ThisKey="PolicyAirCabinGroupItemId" OtherKey="PolicyAirCabinGroupItemId" Type="PolicyAirCabinGroupItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.spDesktopDataAdmin_DeletePolicyAirCabinGroupItem_v1" Method="spDesktopDataAdmin_DeletePolicyAirCabinGroupItem_v1">
    <Parameter Name="PolicyAirCabinGroupItemId" Parameter="policyAirCabinGroupItemId" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="VersionNumber" Parameter="versionNumber" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_InsertPolicyAirCabinGroupItem_v1" Method="spDesktopDataAdmin_InsertPolicyAirCabinGroupItem_v1">
    <Parameter Name="PolicyAirCabinGroupItemId" Parameter="policyAirCabinGroupItemId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="PolicyGroupId" Parameter="policyGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="AirlineCabinCode" Parameter="airlineCabinCode" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="FlightDurationAllowedMin" Parameter="flightDurationAllowedMin" Type="System.Int32" DbType="Int" />
    <Parameter Name="FlightDurationAllowedMax" Parameter="flightDurationAllowedMax" Type="System.Int32" DbType="Int" />
    <Parameter Name="FlightMileageAllowedMin" Parameter="flightMileageAllowedMin" Type="System.Int32" DbType="Int" />
    <Parameter Name="FlightMileageAllowedMax" Parameter="flightMileageAllowedMax" Type="System.Int32" DbType="Int" />
    <Parameter Name="PolicyProhibitedFlag" Parameter="policyProhibitedFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EnabledFlag" Parameter="enabledFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EnabledDate" Parameter="enabledDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ExpiryDate" Parameter="expiryDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="TravelDateValidFrom" Parameter="travelDateValidFrom" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="TravelDateValidTo" Parameter="travelDateValidTo" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="FromGlobalFlag" Parameter="fromGlobalFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FromGlobalRegionCode" Parameter="fromGlobalRegionCode" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="FromGlobalSubRegionCode" Parameter="fromGlobalSubRegionCode" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="FromCountryCode" Parameter="fromCountryCode" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="FromCityCode" Parameter="fromCityCode" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="FromTravelPortCode" Parameter="fromTravelPortCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="FromTraverlPortTypeId" Parameter="fromTraverlPortTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ToGlobalFlag" Parameter="toGlobalFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ToGlobalRegionCode" Parameter="toGlobalRegionCode" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="ToGlobalSubRegionCode" Parameter="toGlobalSubRegionCode" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="ToCountryCode" Parameter="toCountryCode" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="ToCityCode" Parameter="toCityCode" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="ToTravelPortCode" Parameter="toTravelPortCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToTravelPortTypeId" Parameter="toTravelPortTypeId" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="RoutingViceVersaFlag" Parameter="routingViceVersaFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_UpdatePolicyAirCabinGroupItem_v1" Method="spDesktopDataAdmin_UpdatePolicyAirCabinGroupItem_v1">
    <Parameter Name="PolicyAirCabinGroupItemId" Parameter="policyAirCabinGroupItemId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PolicyGroupId" Parameter="policyGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="AirlineCabinCode" Parameter="airlineCabinCode" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="FlightDurationAllowedMin" Parameter="flightDurationAllowedMin" Type="System.Int32" DbType="Int" />
    <Parameter Name="FlightDurationAllowedMax" Parameter="flightDurationAllowedMax" Type="System.Int32" DbType="Int" />
    <Parameter Name="FlightMileageAllowedMin" Parameter="flightMileageAllowedMin" Type="System.Int32" DbType="Int" />
    <Parameter Name="FlightMileageAllowedMax" Parameter="flightMileageAllowedMax" Type="System.Int32" DbType="Int" />
    <Parameter Name="PolicyProhibitedFlag" Parameter="policyProhibitedFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EnabledFlag" Parameter="enabledFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EnabledDate" Parameter="enabledDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ExpiryDate" Parameter="expiryDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="TravelDateValidFrom" Parameter="travelDateValidFrom" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="TravelDateValidTo" Parameter="travelDateValidTo" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="FromGlobalFlag" Parameter="fromGlobalFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FromGlobalRegionCode" Parameter="fromGlobalRegionCode" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="FromGlobalSubRegionCode" Parameter="fromGlobalSubRegionCode" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="FromCountryCode" Parameter="fromCountryCode" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="FromCityCode" Parameter="fromCityCode" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="FromTravelPortCode" Parameter="fromTravelPortCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="FromTraverlPortTypeId" Parameter="fromTraverlPortTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ToGlobalFlag" Parameter="toGlobalFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ToGlobalRegionCode" Parameter="toGlobalRegionCode" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="ToGlobalSubRegionCode" Parameter="toGlobalSubRegionCode" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="ToCountryCode" Parameter="toCountryCode" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="ToCityCode" Parameter="toCityCode" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="ToTravelPortCode" Parameter="toTravelPortCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToTravelPortTypeId" Parameter="toTravelPortTypeId" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="RoutingViceVersaFlag" Parameter="routingViceVersaFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="VersionNumber" Parameter="versionNumber" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_InsertPolicyAirCabinGroupItemAirCabinAdvice_v1" Method="spDesktopDataAdmin_InsertPolicyAirCabinGroupItemAirCabinAdvice_v1">
    <Parameter Name="PolicyAirCabinGroupitemId" Parameter="policyAirCabinGroupitemId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LanguageCode" Parameter="languageCode" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="AirCabinAdvice" Parameter="airCabinAdvice" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAirCabinAdvice_v1" Method="spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAirCabinAdvice_v1">
    <Parameter Name="PolicyAirCabinGroupItemId" Parameter="policyAirCabinGroupItemId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SortField" Parameter="sortField" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SortOrder" Parameter="sortOrder" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageNumber" Parameter="pageNumber" Type="System.Int32" DbType="Int" />
    <ElementType Name="spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAirCabinAdvice_v1Result">
      <Column Name="PolicyAirCabinGroupItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LanguageCode" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="LanguageName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AirCabinAdvice" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="RecordCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_DeletePolicyAirCabinGroupItemAirCabinAdvice_v1" Method="spDesktopDataAdmin_DeletePolicyAirCabinGroupItemAirCabinAdvice_v1">
    <Parameter Name="PolicyAirCabinGroupitemId" Parameter="policyAirCabinGroupitemId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LanguageCode" Parameter="languageCode" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="VersionNumber" Parameter="versionNumber" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_UpdatePolicyAirCabinGroupItemAirCabinAdvice_v1" Method="spDesktopDataAdmin_UpdatePolicyAirCabinGroupItemAirCabinAdvice_v1">
    <Parameter Name="PolicyAirCabinGroupitemId" Parameter="policyAirCabinGroupitemId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LanguageCode" Parameter="languageCode" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="AirCabinAdvice" Parameter="airCabinAdvice" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="VersionNumber" Parameter="versionNumber" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAvailableLanguages_v1" Method="spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAvailableLanguages_v1">
    <Parameter Name="PolicyAirCabinGroupitemId" Parameter="policyAirCabinGroupitemId" Type="System.Int32" DbType="Int" />
    <ElementType Name="spDesktopDataAdmin_SelectPolicyAirCabinGroupItemAvailableLanguages_v1Result">
      <Column Name="LanguageName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LanguageCode" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_SelectPolicyAirCabinGroupItems_v1" Method="spDesktopDataAdmin_SelectPolicyAirCabinGroupItems_v1">
    <Parameter Name="PolicyGroupID" Parameter="policyGroupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SystemUserGuid" Parameter="systemUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="SortField" Parameter="sortField" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SortOrder" Parameter="sortOrder" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PageNumber" Parameter="pageNumber" Type="System.Int32" DbType="Int" />
    <ElementType Name="spDesktopDataAdmin_SelectPolicyAirCabinGroupItems_v1Result">
      <Column Name="PolicyGroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyAirCabinGroupItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FlightDurationAllowedMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlightDurationAllowedMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlightMileageAllowedMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlightMileageAllowedMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AirlineCabinDefaultDescription" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Advice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HasWriteAccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RecordCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>