#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Desktop_Local_v4051")]
	public partial class PolicyAirParameterGroupItemLanguageDC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PolicyAirParameterGroupItemLanguageDC() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Desktop_Local_v4051ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyAirParameterGroupItemLanguageDC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyAirParameterGroupItemLanguageDC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyAirParameterGroupItemLanguageDC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PolicyAirParameterGroupItemLanguageDC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPolicyAirParameterGroupItemLanguages_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPolicyAirParameterGroupItemLanguages_v1Result> spDesktopDataAdmin_SelectPolicyAirParameterGroupItemLanguages_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirParameterGroupItemId", DbType="Int")] System.Nullable<int> policyAirParameterGroupItemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyGroupId", DbType="Int")] System.Nullable<int> policyGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filter", DbType="VarChar(25)")] string filter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortField", DbType="VarChar(50)")] string sortField, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirParameterGroupItemId, policyGroupId, filter, sortField, sortOrder, pageNumber, adminUserGuid);
			return ((ISingleResult<spDesktopDataAdmin_SelectPolicyAirParameterGroupItemLanguages_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_InsertPolicyAirParameterGroupItemLanguage_v1")]
		public int spDesktopDataAdmin_InsertPolicyAirParameterGroupItemLanguage_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirParameterGroupItemId", DbType="Int")] System.Nullable<int> policyAirParameterGroupItemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="NVarChar(5)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Translation", DbType="NVarChar(255)")] string translation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirParameterGroupItemId, languageCode, translation, adminUserGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_DeletePolicyAirParameterGroupItemLanguage_v1")]
		public int spDesktopDataAdmin_DeletePolicyAirParameterGroupItemLanguage_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirParameterGroupItemId", DbType="Int")] System.Nullable<int> policyAirParameterGroupItemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="NVarChar(5)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirParameterGroupItemId, languageCode, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPolicyAirParameterGroupItemAvailableLanguages_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPolicyAirParameterGroupItemAvailableLanguages_v1Result> spDesktopDataAdmin_SelectPolicyAirParameterGroupItemAvailableLanguages_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirParameterGroupItemId", DbType="Int")] System.Nullable<int> policyAirParameterGroupItemId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirParameterGroupItemId);
			return ((ISingleResult<spDesktopDataAdmin_SelectPolicyAirParameterGroupItemAvailableLanguages_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_UpdatePolicyAirParameterGroupItemLanguage_v1")]
		public int spDesktopDataAdmin_UpdatePolicyAirParameterGroupItemLanguage_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolicyAirParameterGroupItemId", DbType="Int")] System.Nullable<int> policyAirParameterGroupItemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="NVarChar(5)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Translation", DbType="NVarChar(255)")] string translation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), policyAirParameterGroupItemId, languageCode, translation, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPolicyAirParameterGroupItemLanguages_v1Result
	{
		
		private System.Nullable<int> _PolicyAirParameterGroupItemId;
		
		private System.Nullable<int> _PolicyGroupId;
		
		private string _Translation;
		
		private string _LanguageCode;
		
		private string _LanguageName;
		
		private System.Nullable<bool> _HasWriteAccess;
		
		private System.Nullable<int> _RecordCount;
		
		public spDesktopDataAdmin_SelectPolicyAirParameterGroupItemLanguages_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyAirParameterGroupItemId", DbType="Int")]
		public System.Nullable<int> PolicyAirParameterGroupItemId
		{
			get
			{
				return this._PolicyAirParameterGroupItemId;
			}
			set
			{
				if ((this._PolicyAirParameterGroupItemId != value))
				{
					this._PolicyAirParameterGroupItemId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyGroupId", DbType="Int")]
		public System.Nullable<int> PolicyGroupId
		{
			get
			{
				return this._PolicyGroupId;
			}
			set
			{
				if ((this._PolicyGroupId != value))
				{
					this._PolicyGroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Translation", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Translation
		{
			get
			{
				return this._Translation;
			}
			set
			{
				if ((this._Translation != value))
				{
					this._Translation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NVarChar(5)")]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this._LanguageCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageName", DbType="NVarChar(50)")]
		public string LanguageName
		{
			get
			{
				return this._LanguageName;
			}
			set
			{
				if ((this._LanguageName != value))
				{
					this._LanguageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasWriteAccess", DbType="Bit")]
		public System.Nullable<bool> HasWriteAccess
		{
			get
			{
				return this._HasWriteAccess;
			}
			set
			{
				if ((this._HasWriteAccess != value))
				{
					this._HasWriteAccess = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCount", DbType="Int")]
		public System.Nullable<int> RecordCount
		{
			get
			{
				return this._RecordCount;
			}
			set
			{
				if ((this._RecordCount != value))
				{
					this._RecordCount = value;
				}
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPolicyAirParameterGroupItemAvailableLanguages_v1Result
	{
		
		private string _LanguageName;
		
		private string _LanguageCode;
		
		public spDesktopDataAdmin_SelectPolicyAirParameterGroupItemAvailableLanguages_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LanguageName
		{
			get
			{
				return this._LanguageName;
			}
			set
			{
				if ((this._LanguageName != value))
				{
					this._LanguageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this._LanguageCode = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
