#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DesktopData")]
	public partial class PublicHolidayDateDC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPublicHolidayGroupHolidayDate(PublicHolidayGroupHolidayDate instance);
    partial void UpdatePublicHolidayGroupHolidayDate(PublicHolidayGroupHolidayDate instance);
    partial void DeletePublicHolidayGroupHolidayDate(PublicHolidayGroupHolidayDate instance);
    #endregion
		
		public PublicHolidayDateDC() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CWTDesktopDatabase"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PublicHolidayDateDC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PublicHolidayDateDC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PublicHolidayDateDC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PublicHolidayDateDC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PublicHolidayGroupHolidayDate> PublicHolidayGroupHolidayDates
		{
			get
			{
				return this.GetTable<PublicHolidayGroupHolidayDate>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_InsertPublicHolidayDate_v1")]
		public int spDesktopDataAdmin_InsertPublicHolidayDate_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublicHolidayDate", DbType="DateTime")] System.Nullable<System.DateTime> publicHolidayDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublicHolidayDescription", DbType="NVarChar(50)")] string publicHolidayDescription, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublicHolidayGroupId", DbType="Int")] System.Nullable<int> publicHolidayGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), publicHolidayDate, publicHolidayDescription, publicHolidayGroupId, adminUserGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_UpdatePublicHolidayDate_v1")]
		public int spDesktopDataAdmin_UpdatePublicHolidayDate_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublicHolidayDateId", DbType="Int")] System.Nullable<int> publicHolidayDateId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublicHolidayDate", DbType="DateTime")] System.Nullable<System.DateTime> publicHolidayDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublicHolidayDescription", DbType="NVarChar(50)")] string publicHolidayDescription, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), publicHolidayDateId, publicHolidayDate, publicHolidayDescription, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPublicHolidayDates_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPublicHolidayDates_v1Result> spDesktopDataAdmin_SelectPublicHolidayDates_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublicHolidayGroupId", DbType="Int")] System.Nullable<int> publicHolidayGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filter", DbType="VarChar(50)")] string filter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortField", DbType="VarChar(50)")] string sortField, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), publicHolidayGroupId, filter, sortField, sortOrder, pageNumber);
			return ((ISingleResult<spDesktopDataAdmin_SelectPublicHolidayDates_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_DeletePublicHolidayDate_v1")]
		public int spDesktopDataAdmin_DeletePublicHolidayDate_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublicHolidayDateId", DbType="Int")] System.Nullable<int> publicHolidayDateId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), publicHolidayDateId, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PublicHolidayDate")]
	public partial class PublicHolidayGroupHolidayDate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PublicHolidayDateId;
		
		private System.DateTime _PublicHolidayDate1;
		
		private string _PublicHolidayDescription;
		
		private int _PublicHolidayGroupId;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private System.Nullable<int> _VersionNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPublicHolidayDateIdChanging(int value);
    partial void OnPublicHolidayDateIdChanged();
    partial void OnPublicHolidayDate1Changing(System.DateTime value);
    partial void OnPublicHolidayDate1Changed();
    partial void OnPublicHolidayDescriptionChanging(string value);
    partial void OnPublicHolidayDescriptionChanged();
    partial void OnPublicHolidayGroupIdChanging(int value);
    partial void OnPublicHolidayGroupIdChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(System.Nullable<int> value);
    partial void OnVersionNumberChanged();
    #endregion
		
		public PublicHolidayGroupHolidayDate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicHolidayDateId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PublicHolidayDateId
		{
			get
			{
				return this._PublicHolidayDateId;
			}
			set
			{
				if ((this._PublicHolidayDateId != value))
				{
					this.OnPublicHolidayDateIdChanging(value);
					this.SendPropertyChanging();
					this._PublicHolidayDateId = value;
					this.SendPropertyChanged("PublicHolidayDateId");
					this.OnPublicHolidayDateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PublicHolidayDate", Storage="_PublicHolidayDate1", DbType="DateTime NOT NULL")]
		public System.DateTime PublicHolidayDate1
		{
			get
			{
				return this._PublicHolidayDate1;
			}
			set
			{
				if ((this._PublicHolidayDate1 != value))
				{
					this.OnPublicHolidayDate1Changing(value);
					this.SendPropertyChanging();
					this._PublicHolidayDate1 = value;
					this.SendPropertyChanged("PublicHolidayDate1");
					this.OnPublicHolidayDate1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicHolidayDescription", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PublicHolidayDescription
		{
			get
			{
				return this._PublicHolidayDescription;
			}
			set
			{
				if ((this._PublicHolidayDescription != value))
				{
					this.OnPublicHolidayDescriptionChanging(value);
					this.SendPropertyChanging();
					this._PublicHolidayDescription = value;
					this.SendPropertyChanged("PublicHolidayDescription");
					this.OnPublicHolidayDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicHolidayGroupId", DbType="Int NOT NULL")]
		public int PublicHolidayGroupId
		{
			get
			{
				return this._PublicHolidayGroupId;
			}
			set
			{
				if ((this._PublicHolidayGroupId != value))
				{
					this.OnPublicHolidayGroupIdChanging(value);
					this.SendPropertyChanging();
					this._PublicHolidayGroupId = value;
					this.SendPropertyChanged("PublicHolidayGroupId");
					this.OnPublicHolidayGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int")]
		public System.Nullable<int> VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPublicHolidayDates_v1Result
	{
		
		private int _PublicHolidayDateId;
		
		private System.DateTime _PublicHolidayDate;
		
		private string _PublicHolidayDescription;
		
		private System.Nullable<int> _RecordCount;
		
		public spDesktopDataAdmin_SelectPublicHolidayDates_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicHolidayDateId", DbType="Int NOT NULL")]
		public int PublicHolidayDateId
		{
			get
			{
				return this._PublicHolidayDateId;
			}
			set
			{
				if ((this._PublicHolidayDateId != value))
				{
					this._PublicHolidayDateId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicHolidayDate", DbType="DateTime NOT NULL")]
		public System.DateTime PublicHolidayDate
		{
			get
			{
				return this._PublicHolidayDate;
			}
			set
			{
				if ((this._PublicHolidayDate != value))
				{
					this._PublicHolidayDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicHolidayDescription", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PublicHolidayDescription
		{
			get
			{
				return this._PublicHolidayDescription;
			}
			set
			{
				if ((this._PublicHolidayDescription != value))
				{
					this._PublicHolidayDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCount", DbType="Int")]
		public System.Nullable<int> RecordCount
		{
			get
			{
				return this._RecordCount;
			}
			set
			{
				if ((this._RecordCount != value))
				{
					this._RecordCount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
