#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Desktop_Local_v1841")]
	public partial class PublicHolidayGroupDC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPublicHolidayGroup(PublicHolidayGroup instance);
    partial void UpdatePublicHolidayGroup(PublicHolidayGroup instance);
    partial void DeletePublicHolidayGroup(PublicHolidayGroup instance);
    partial void InsertPublicHolidayGroupLocation(PublicHolidayGroupLocation instance);
    partial void UpdatePublicHolidayGroupLocation(PublicHolidayGroupLocation instance);
    partial void DeletePublicHolidayGroupLocation(PublicHolidayGroupLocation instance);
    partial void InsertPublicHolidayGroupTeam(PublicHolidayGroupTeam instance);
    partial void UpdatePublicHolidayGroupTeam(PublicHolidayGroupTeam instance);
    partial void DeletePublicHolidayGroupTeam(PublicHolidayGroupTeam instance);
    #endregion
		
		public PublicHolidayGroupDC() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Desktop_Local_v1841"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PublicHolidayGroupDC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PublicHolidayGroupDC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PublicHolidayGroupDC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PublicHolidayGroupDC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PublicHolidayGroup> PublicHolidayGroups
		{
			get
			{
				return this.GetTable<PublicHolidayGroup>();
			}
		}
		
		public System.Data.Linq.Table<PublicHolidayGroupLocation> PublicHolidayGroupLocations
		{
			get
			{
				return this.GetTable<PublicHolidayGroupLocation>();
			}
		}
		
		public System.Data.Linq.Table<PublicHolidayGroupTeam> PublicHolidayGroupTeams
		{
			get
			{
				return this.GetTable<PublicHolidayGroupTeam>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_InsertPublicHolidayGroup_v1")]
		public int spDesktopDataAdmin_InsertPublicHolidayGroup_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublicHolidayGroupName", DbType="NVarChar(100)")] string publicHolidayGroupName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledFlag", DbType="Bit")] System.Nullable<bool> enabledFlag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledDate", DbType="DateTime")] System.Nullable<System.DateTime> enabledDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpiryDate", DbType="DateTime")] System.Nullable<System.DateTime> expiryDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HierarchyType", DbType="VarChar(100)")] string hierarchyType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HierarchyItemCode", DbType="VarChar(13)")] string hierarchyItemCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelerTypeGuid", DbType="VarChar(13)")] string travelerTypeGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientSubUnitGuid", DbType="VarChar(13)")] string clientSubUnitGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SourceSystemCode", DbType="NVarChar(10)")] string sourceSystemCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), publicHolidayGroupName, enabledFlag, enabledDate, expiryDate, hierarchyType, hierarchyItemCode, travelerTypeGuid, clientSubUnitGuid, sourceSystemCode, adminUserGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_UpdatePublicHolidayGroup_v1")]
		public int spDesktopDataAdmin_UpdatePublicHolidayGroup_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublicHolidayGroupId", DbType="Int")] System.Nullable<int> publicHolidayGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublicHolidayGroupName", DbType="NVarChar(50)")] string publicHolidayGroupName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledFlag", DbType="Bit")] System.Nullable<bool> enabledFlag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnabledDate", DbType="DateTime")] System.Nullable<System.DateTime> enabledDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpiryDate", DbType="DateTime")] System.Nullable<System.DateTime> expiryDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HierarchyType", DbType="VarChar(100)")] string hierarchyType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HierarchyItemCode", DbType="VarChar(13)")] string hierarchyItemCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelerTypeGuid", DbType="VarChar(13)")] string travelerTypeGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientSubUnitGuid", DbType="VarChar(13)")] string clientSubUnitGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SourceSystemCode", DbType="NVarChar(10)")] string sourceSystemCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), publicHolidayGroupId, publicHolidayGroupName, enabledFlag, enabledDate, expiryDate, hierarchyType, hierarchyItemCode, travelerTypeGuid, clientSubUnitGuid, sourceSystemCode, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPublicHolidayGroups_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPublicHolidayGroups_v1Result> spDesktopDataAdmin_SelectPublicHolidayGroups_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filter", DbType="VarChar(25)")] string filter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortField", DbType="VarChar(50)")] string sortField, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), filter, sortField, sortOrder, pageNumber, adminUserGuid);
			return ((ISingleResult<spDesktopDataAdmin_SelectPublicHolidayGroups_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_DeletePublicHolidayGroup_v1")]
		public int spDesktopDataAdmin_DeletePublicHolidayGroup_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublicHolidayGroupId", DbType="Int")] System.Nullable<int> publicHolidayGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), publicHolidayGroupId, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectPublicHolidayGroupsOrphaned_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectPublicHolidayGroupsOrphaned_v1Result> spDesktopDataAdmin_SelectPublicHolidayGroupsOrphaned_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filter", DbType="VarChar(25)")] string filter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortField", DbType="VarChar(50)")] string sortField, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), filter, sortField, sortOrder, pageNumber, adminUserGuid);
			return ((ISingleResult<spDesktopDataAdmin_SelectPublicHolidayGroupsOrphaned_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fnDesktopDataAdmin_SelectPublicHolidayGroupHierarchy_v1", IsComposable=true)]
		public IQueryable<fnDesktopDataAdmin_SelectPublicHolidayGroupHierarchy_v1Result> fnDesktopDataAdmin_SelectPublicHolidayGroupHierarchy_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublicHolidayGroupId", DbType="Int")] System.Nullable<int> publicHolidayGroupId)
		{
			return this.CreateMethodCallQuery<fnDesktopDataAdmin_SelectPublicHolidayGroupHierarchy_v1Result>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), publicHolidayGroupId);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PublicHolidayGroup")]
	public partial class PublicHolidayGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PublicHolidayGroupId;
		
		private string _PublicHolidayGroupName;
		
		private bool _EnabledFlag;
		
		private System.DateTime _EnabledDate;
		
		private System.Nullable<System.DateTime> _ExpiryDate;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private System.Nullable<int> _VersionNumber;
		
		private EntitySet<PublicHolidayGroupLocation> _PublicHolidayGroupLocations;
		
		private EntitySet<PublicHolidayGroupTeam> _PublicHolidayGroupTeams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPublicHolidayGroupIdChanging(int value);
    partial void OnPublicHolidayGroupIdChanged();
    partial void OnPublicHolidayGroupNameChanging(string value);
    partial void OnPublicHolidayGroupNameChanged();
    partial void OnEnabledFlagChanging(bool value);
    partial void OnEnabledFlagChanged();
    partial void OnEnabledDateChanging(System.DateTime value);
    partial void OnEnabledDateChanged();
    partial void OnExpiryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpiryDateChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(System.Nullable<int> value);
    partial void OnVersionNumberChanged();
    #endregion
		
		public PublicHolidayGroup()
		{
			this._PublicHolidayGroupLocations = new EntitySet<PublicHolidayGroupLocation>(new Action<PublicHolidayGroupLocation>(this.attach_PublicHolidayGroupLocations), new Action<PublicHolidayGroupLocation>(this.detach_PublicHolidayGroupLocations));
			this._PublicHolidayGroupTeams = new EntitySet<PublicHolidayGroupTeam>(new Action<PublicHolidayGroupTeam>(this.attach_PublicHolidayGroupTeams), new Action<PublicHolidayGroupTeam>(this.detach_PublicHolidayGroupTeams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicHolidayGroupId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PublicHolidayGroupId
		{
			get
			{
				return this._PublicHolidayGroupId;
			}
			set
			{
				if ((this._PublicHolidayGroupId != value))
				{
					this.OnPublicHolidayGroupIdChanging(value);
					this.SendPropertyChanging();
					this._PublicHolidayGroupId = value;
					this.SendPropertyChanged("PublicHolidayGroupId");
					this.OnPublicHolidayGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicHolidayGroupName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PublicHolidayGroupName
		{
			get
			{
				return this._PublicHolidayGroupName;
			}
			set
			{
				if ((this._PublicHolidayGroupName != value))
				{
					this.OnPublicHolidayGroupNameChanging(value);
					this.SendPropertyChanging();
					this._PublicHolidayGroupName = value;
					this.SendPropertyChanged("PublicHolidayGroupName");
					this.OnPublicHolidayGroupNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnabledFlag", DbType="Bit NOT NULL")]
		public bool EnabledFlag
		{
			get
			{
				return this._EnabledFlag;
			}
			set
			{
				if ((this._EnabledFlag != value))
				{
					this.OnEnabledFlagChanging(value);
					this.SendPropertyChanging();
					this._EnabledFlag = value;
					this.SendPropertyChanged("EnabledFlag");
					this.OnEnabledFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnabledDate", DbType="DateTime NOT NULL")]
		public System.DateTime EnabledDate
		{
			get
			{
				return this._EnabledDate;
			}
			set
			{
				if ((this._EnabledDate != value))
				{
					this.OnEnabledDateChanging(value);
					this.SendPropertyChanging();
					this._EnabledDate = value;
					this.SendPropertyChanged("EnabledDate");
					this.OnEnabledDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpiryDate
		{
			get
			{
				return this._ExpiryDate;
			}
			set
			{
				if ((this._ExpiryDate != value))
				{
					this.OnExpiryDateChanging(value);
					this.SendPropertyChanging();
					this._ExpiryDate = value;
					this.SendPropertyChanged("ExpiryDate");
					this.OnExpiryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int")]
		public System.Nullable<int> VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PublicHolidayGroup_PublicHolidayGroupLocation", Storage="_PublicHolidayGroupLocations", ThisKey="PublicHolidayGroupId", OtherKey="PublicHolidayGroupId")]
		public EntitySet<PublicHolidayGroupLocation> PublicHolidayGroupLocations
		{
			get
			{
				return this._PublicHolidayGroupLocations;
			}
			set
			{
				this._PublicHolidayGroupLocations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PublicHolidayGroup_PublicHolidayGroupTeam", Storage="_PublicHolidayGroupTeams", ThisKey="PublicHolidayGroupId", OtherKey="PublicHolidayGroupId")]
		public EntitySet<PublicHolidayGroupTeam> PublicHolidayGroupTeams
		{
			get
			{
				return this._PublicHolidayGroupTeams;
			}
			set
			{
				this._PublicHolidayGroupTeams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PublicHolidayGroupLocations(PublicHolidayGroupLocation entity)
		{
			this.SendPropertyChanging();
			entity.PublicHolidayGroup = this;
		}
		
		private void detach_PublicHolidayGroupLocations(PublicHolidayGroupLocation entity)
		{
			this.SendPropertyChanging();
			entity.PublicHolidayGroup = null;
		}
		
		private void attach_PublicHolidayGroupTeams(PublicHolidayGroupTeam entity)
		{
			this.SendPropertyChanging();
			entity.PublicHolidayGroup = this;
		}
		
		private void detach_PublicHolidayGroupTeams(PublicHolidayGroupTeam entity)
		{
			this.SendPropertyChanging();
			entity.PublicHolidayGroup = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PublicHolidayGroupLocation")]
	public partial class PublicHolidayGroupLocation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PublicHolidayGroupId;
		
		private int _LocationId;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private int _VersionNumber;
		
		private EntityRef<PublicHolidayGroup> _PublicHolidayGroup;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPublicHolidayGroupIdChanging(int value);
    partial void OnPublicHolidayGroupIdChanged();
    partial void OnLocationIdChanging(int value);
    partial void OnLocationIdChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(int value);
    partial void OnVersionNumberChanged();
    #endregion
		
		public PublicHolidayGroupLocation()
		{
			this._PublicHolidayGroup = default(EntityRef<PublicHolidayGroup>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicHolidayGroupId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PublicHolidayGroupId
		{
			get
			{
				return this._PublicHolidayGroupId;
			}
			set
			{
				if ((this._PublicHolidayGroupId != value))
				{
					if (this._PublicHolidayGroup.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPublicHolidayGroupIdChanging(value);
					this.SendPropertyChanging();
					this._PublicHolidayGroupId = value;
					this.SendPropertyChanged("PublicHolidayGroupId");
					this.OnPublicHolidayGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int LocationId
		{
			get
			{
				return this._LocationId;
			}
			set
			{
				if ((this._LocationId != value))
				{
					this.OnLocationIdChanging(value);
					this.SendPropertyChanging();
					this._LocationId = value;
					this.SendPropertyChanged("LocationId");
					this.OnLocationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int NOT NULL")]
		public int VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PublicHolidayGroup_PublicHolidayGroupLocation", Storage="_PublicHolidayGroup", ThisKey="PublicHolidayGroupId", OtherKey="PublicHolidayGroupId", IsForeignKey=true)]
		public PublicHolidayGroup PublicHolidayGroup
		{
			get
			{
				return this._PublicHolidayGroup.Entity;
			}
			set
			{
				PublicHolidayGroup previousValue = this._PublicHolidayGroup.Entity;
				if (((previousValue != value) 
							|| (this._PublicHolidayGroup.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PublicHolidayGroup.Entity = null;
						previousValue.PublicHolidayGroupLocations.Remove(this);
					}
					this._PublicHolidayGroup.Entity = value;
					if ((value != null))
					{
						value.PublicHolidayGroupLocations.Add(this);
						this._PublicHolidayGroupId = value.PublicHolidayGroupId;
					}
					else
					{
						this._PublicHolidayGroupId = default(int);
					}
					this.SendPropertyChanged("PublicHolidayGroup");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PublicHolidayGroupTeam")]
	public partial class PublicHolidayGroupTeam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PublicHolidayGroupId;
		
		private int _TeamId;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private int _VersionNumber;
		
		private EntityRef<PublicHolidayGroup> _PublicHolidayGroup;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPublicHolidayGroupIdChanging(int value);
    partial void OnPublicHolidayGroupIdChanged();
    partial void OnTeamIdChanging(int value);
    partial void OnTeamIdChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(int value);
    partial void OnVersionNumberChanged();
    #endregion
		
		public PublicHolidayGroupTeam()
		{
			this._PublicHolidayGroup = default(EntityRef<PublicHolidayGroup>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicHolidayGroupId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PublicHolidayGroupId
		{
			get
			{
				return this._PublicHolidayGroupId;
			}
			set
			{
				if ((this._PublicHolidayGroupId != value))
				{
					if (this._PublicHolidayGroup.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPublicHolidayGroupIdChanging(value);
					this.SendPropertyChanging();
					this._PublicHolidayGroupId = value;
					this.SendPropertyChanged("PublicHolidayGroupId");
					this.OnPublicHolidayGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TeamId
		{
			get
			{
				return this._TeamId;
			}
			set
			{
				if ((this._TeamId != value))
				{
					this.OnTeamIdChanging(value);
					this.SendPropertyChanging();
					this._TeamId = value;
					this.SendPropertyChanged("TeamId");
					this.OnTeamIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int NOT NULL")]
		public int VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PublicHolidayGroup_PublicHolidayGroupTeam", Storage="_PublicHolidayGroup", ThisKey="PublicHolidayGroupId", OtherKey="PublicHolidayGroupId", IsForeignKey=true)]
		public PublicHolidayGroup PublicHolidayGroup
		{
			get
			{
				return this._PublicHolidayGroup.Entity;
			}
			set
			{
				PublicHolidayGroup previousValue = this._PublicHolidayGroup.Entity;
				if (((previousValue != value) 
							|| (this._PublicHolidayGroup.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PublicHolidayGroup.Entity = null;
						previousValue.PublicHolidayGroupTeams.Remove(this);
					}
					this._PublicHolidayGroup.Entity = value;
					if ((value != null))
					{
						value.PublicHolidayGroupTeams.Add(this);
						this._PublicHolidayGroupId = value.PublicHolidayGroupId;
					}
					else
					{
						this._PublicHolidayGroupId = default(int);
					}
					this.SendPropertyChanged("PublicHolidayGroup");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPublicHolidayGroups_v1Result
	{
		
		private int _PublicHolidayGroupId;
		
		private string _PublicHolidayGroupName;
		
		private System.DateTime _EnabledDate;
		
		private string _HierarchyType;
		
		private System.Nullable<bool> _HasWriteAccess;
		
		private System.Nullable<int> _RecordCount;
		
		public spDesktopDataAdmin_SelectPublicHolidayGroups_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicHolidayGroupId", DbType="Int NOT NULL")]
		public int PublicHolidayGroupId
		{
			get
			{
				return this._PublicHolidayGroupId;
			}
			set
			{
				if ((this._PublicHolidayGroupId != value))
				{
					this._PublicHolidayGroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicHolidayGroupName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PublicHolidayGroupName
		{
			get
			{
				return this._PublicHolidayGroupName;
			}
			set
			{
				if ((this._PublicHolidayGroupName != value))
				{
					this._PublicHolidayGroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnabledDate", DbType="DateTime NOT NULL")]
		public System.DateTime EnabledDate
		{
			get
			{
				return this._EnabledDate;
			}
			set
			{
				if ((this._EnabledDate != value))
				{
					this._EnabledDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HierarchyType", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string HierarchyType
		{
			get
			{
				return this._HierarchyType;
			}
			set
			{
				if ((this._HierarchyType != value))
				{
					this._HierarchyType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasWriteAccess", DbType="Bit")]
		public System.Nullable<bool> HasWriteAccess
		{
			get
			{
				return this._HasWriteAccess;
			}
			set
			{
				if ((this._HasWriteAccess != value))
				{
					this._HasWriteAccess = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCount", DbType="Int")]
		public System.Nullable<int> RecordCount
		{
			get
			{
				return this._RecordCount;
			}
			set
			{
				if ((this._RecordCount != value))
				{
					this._RecordCount = value;
				}
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectPublicHolidayGroupsOrphaned_v1Result
	{
		
		private int _PublicHolidayGroupId;
		
		private string _PublicHolidayGroupName;
		
		private System.Nullable<bool> _HasWriteAccess;
		
		private System.Nullable<int> _RecordCount;
		
		public spDesktopDataAdmin_SelectPublicHolidayGroupsOrphaned_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicHolidayGroupId", DbType="Int NOT NULL")]
		public int PublicHolidayGroupId
		{
			get
			{
				return this._PublicHolidayGroupId;
			}
			set
			{
				if ((this._PublicHolidayGroupId != value))
				{
					this._PublicHolidayGroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicHolidayGroupName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PublicHolidayGroupName
		{
			get
			{
				return this._PublicHolidayGroupName;
			}
			set
			{
				if ((this._PublicHolidayGroupName != value))
				{
					this._PublicHolidayGroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasWriteAccess", DbType="Bit")]
		public System.Nullable<bool> HasWriteAccess
		{
			get
			{
				return this._HasWriteAccess;
			}
			set
			{
				if ((this._HasWriteAccess != value))
				{
					this._HasWriteAccess = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCount", DbType="Int")]
		public System.Nullable<int> RecordCount
		{
			get
			{
				return this._RecordCount;
			}
			set
			{
				if ((this._RecordCount != value))
				{
					this._RecordCount = value;
				}
			}
		}
	}
	
	public partial class fnDesktopDataAdmin_SelectPublicHolidayGroupHierarchy_v1Result
	{
		
		private string _HierarchyCode;
		
		private string _HierarchyName;
		
		private string _HierarchyType;
		
		private string _TravelerTypeGuid;
		
		private string _TravelerTypeName;
		
		private string _SourceSystemCode;
		
		public fnDesktopDataAdmin_SelectPublicHolidayGroupHierarchy_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HierarchyCode", DbType="VarChar(13)")]
		public string HierarchyCode
		{
			get
			{
				return this._HierarchyCode;
			}
			set
			{
				if ((this._HierarchyCode != value))
				{
					this._HierarchyCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HierarchyName", DbType="NVarChar(150)")]
		public string HierarchyName
		{
			get
			{
				return this._HierarchyName;
			}
			set
			{
				if ((this._HierarchyName != value))
				{
					this._HierarchyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HierarchyType", DbType="VarChar(100)")]
		public string HierarchyType
		{
			get
			{
				return this._HierarchyType;
			}
			set
			{
				if ((this._HierarchyType != value))
				{
					this._HierarchyType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelerTypeGuid", DbType="VarChar(13)")]
		public string TravelerTypeGuid
		{
			get
			{
				return this._TravelerTypeGuid;
			}
			set
			{
				if ((this._TravelerTypeGuid != value))
				{
					this._TravelerTypeGuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelerTypeName", DbType="VarChar(50)")]
		public string TravelerTypeName
		{
			get
			{
				return this._TravelerTypeName;
			}
			set
			{
				if ((this._TravelerTypeName != value))
				{
					this._TravelerTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceSystemCode", DbType="NVarChar(10)")]
		public string SourceSystemCode
		{
			get
			{
				return this._SourceSystemCode;
			}
			set
			{
				if ((this._SourceSystemCode != value))
				{
					this._SourceSystemCode = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
