#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DesktopData")]
	public partial class ReasonCodeProductTypeDC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertReasonCodeProductType(ReasonCodeProductType instance);
    partial void UpdateReasonCodeProductType(ReasonCodeProductType instance);
    partial void DeleteReasonCodeProductType(ReasonCodeProductType instance);
    #endregion
		
		public ReasonCodeProductTypeDC() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CWTDesktopDatabase"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ReasonCodeProductTypeDC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReasonCodeProductTypeDC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReasonCodeProductTypeDC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReasonCodeProductTypeDC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ReasonCodeProductType> ReasonCodeProductTypes
		{
			get
			{
				return this.GetTable<ReasonCodeProductType>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectReasonCodes_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectReasonCodes_v1Result> spDesktopDataAdmin_SelectReasonCodes_v1()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spDesktopDataAdmin_SelectReasonCodes_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectReasonCodeProductTypes_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectReasonCodeProductTypes_v1Result> spDesktopDataAdmin_SelectReasonCodeProductTypes_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filter", DbType="VarChar(50)")] string filter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortField", DbType="VarChar(50)")] string sortField, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), filter, sortField, sortOrder, pageNumber);
			return ((ISingleResult<spDesktopDataAdmin_SelectReasonCodeProductTypes_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectReasonCodeItemAvailableReasonCodeTypes_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectReasonCodeItemAvailableReasonCodeTypes_v1Result> spDesktopDataAdmin_SelectReasonCodeItemAvailableReasonCodeTypes_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCodeItemId", DbType="Int")] System.Nullable<int> reasonCodeItemId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCodeGroupId", DbType="Int")] System.Nullable<int> reasonCodeGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCode", DbType="VarChar(3)")] string reasonCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reasonCodeItemId, reasonCodeGroupId, reasonCode, productId);
			return ((ISingleResult<spDesktopDataAdmin_SelectReasonCodeItemAvailableReasonCodeTypes_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectReasonCodeProducts_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectReasonCodeProducts_v1Result> spDesktopDataAdmin_SelectReasonCodeProducts_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCode", DbType="VarChar(3)")] string reasonCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reasonCode);
			return ((ISingleResult<spDesktopDataAdmin_SelectReasonCodeProducts_v1Result>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReasonCodeProductType")]
	public partial class ReasonCodeProductType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ReasonCode;
		
		private int _ProductId;
		
		private int _ReasonCodeTypeId;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private int _VersionNumber;
		
		private System.Nullable<int> _ReasonCodeSavingTypeId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReasonCodeChanging(string value);
    partial void OnReasonCodeChanged();
    partial void OnProductIdChanging(int value);
    partial void OnProductIdChanged();
    partial void OnReasonCodeTypeIdChanging(int value);
    partial void OnReasonCodeTypeIdChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(int value);
    partial void OnVersionNumberChanged();
    partial void OnReasonCodeSavingTypeIdChanging(System.Nullable<int> value);
    partial void OnReasonCodeSavingTypeIdChanged();
    #endregion
		
		public ReasonCodeProductType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonCode", DbType="VarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ReasonCode
		{
			get
			{
				return this._ReasonCode;
			}
			set
			{
				if ((this._ReasonCode != value))
				{
					this.OnReasonCodeChanging(value);
					this.SendPropertyChanging();
					this._ReasonCode = value;
					this.SendPropertyChanged("ReasonCode");
					this.OnReasonCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonCodeTypeId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ReasonCodeTypeId
		{
			get
			{
				return this._ReasonCodeTypeId;
			}
			set
			{
				if ((this._ReasonCodeTypeId != value))
				{
					this.OnReasonCodeTypeIdChanging(value);
					this.SendPropertyChanging();
					this._ReasonCodeTypeId = value;
					this.SendPropertyChanged("ReasonCodeTypeId");
					this.OnReasonCodeTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int NOT NULL")]
		public int VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonCodeSavingTypeId", DbType="Int")]
		public System.Nullable<int> ReasonCodeSavingTypeId
		{
			get
			{
				return this._ReasonCodeSavingTypeId;
			}
			set
			{
				if ((this._ReasonCodeSavingTypeId != value))
				{
					this.OnReasonCodeSavingTypeIdChanging(value);
					this.SendPropertyChanging();
					this._ReasonCodeSavingTypeId = value;
					this.SendPropertyChanged("ReasonCodeSavingTypeId");
					this.OnReasonCodeSavingTypeIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectReasonCodes_v1Result
	{
		
		private string _ReasonCode;
		
		public spDesktopDataAdmin_SelectReasonCodes_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonCode", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ReasonCode
		{
			get
			{
				return this._ReasonCode;
			}
			set
			{
				if ((this._ReasonCode != value))
				{
					this._ReasonCode = value;
				}
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectReasonCodeProductTypes_v1Result
	{
		
		private string _ReasonCode;
		
		private int _ReasonCodeTypeId;
		
		private string _ReasonCodeTypeDescription;
		
		private int _ProductId;
		
		private string _ProductName;
		
		private System.Nullable<int> _RecordCount;
		
		public spDesktopDataAdmin_SelectReasonCodeProductTypes_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonCode", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ReasonCode
		{
			get
			{
				return this._ReasonCode;
			}
			set
			{
				if ((this._ReasonCode != value))
				{
					this._ReasonCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonCodeTypeId", DbType="Int NOT NULL")]
		public int ReasonCodeTypeId
		{
			get
			{
				return this._ReasonCodeTypeId;
			}
			set
			{
				if ((this._ReasonCodeTypeId != value))
				{
					this._ReasonCodeTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonCodeTypeDescription", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ReasonCodeTypeDescription
		{
			get
			{
				return this._ReasonCodeTypeDescription;
			}
			set
			{
				if ((this._ReasonCodeTypeDescription != value))
				{
					this._ReasonCodeTypeDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int NOT NULL")]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCount", DbType="Int")]
		public System.Nullable<int> RecordCount
		{
			get
			{
				return this._RecordCount;
			}
			set
			{
				if ((this._RecordCount != value))
				{
					this._RecordCount = value;
				}
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectReasonCodeItemAvailableReasonCodeTypes_v1Result
	{
		
		private int _ReasonCodeTypeId;
		
		private string _ReasonCodeTypeDescription;
		
		public spDesktopDataAdmin_SelectReasonCodeItemAvailableReasonCodeTypes_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonCodeTypeId", DbType="Int NOT NULL")]
		public int ReasonCodeTypeId
		{
			get
			{
				return this._ReasonCodeTypeId;
			}
			set
			{
				if ((this._ReasonCodeTypeId != value))
				{
					this._ReasonCodeTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonCodeTypeDescription", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ReasonCodeTypeDescription
		{
			get
			{
				return this._ReasonCodeTypeDescription;
			}
			set
			{
				if ((this._ReasonCodeTypeDescription != value))
				{
					this._ReasonCodeTypeDescription = value;
				}
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectReasonCodeProducts_v1Result
	{
		
		private int _ProductId;
		
		private string _ProductName;
		
		public spDesktopDataAdmin_SelectReasonCodeProducts_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int NOT NULL")]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
