#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DesktopData")]
	public partial class ReasonCodeProductTypeDescriptionDC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertReasonCodeProductTypeDescription(ReasonCodeProductTypeDescription instance);
    partial void UpdateReasonCodeProductTypeDescription(ReasonCodeProductTypeDescription instance);
    partial void DeleteReasonCodeProductTypeDescription(ReasonCodeProductTypeDescription instance);
    #endregion
		
		public ReasonCodeProductTypeDescriptionDC() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CWTDesktopDatabase"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ReasonCodeProductTypeDescriptionDC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReasonCodeProductTypeDescriptionDC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReasonCodeProductTypeDescriptionDC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReasonCodeProductTypeDescriptionDC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ReasonCodeProductTypeDescription> ReasonCodeProductTypeDescriptions
		{
			get
			{
				return this.GetTable<ReasonCodeProductTypeDescription>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_DeleteReasonCodeProductTypeDescription_v1")]
		public int spDesktopDataAdmin_DeleteReasonCodeProductTypeDescription_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCode", DbType="VarChar(3)")] string reasonCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCodeTypeId", DbType="Int")] System.Nullable<int> reasonCodeTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="NVarChar(5)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reasonCode, productId, reasonCodeTypeId, languageCode, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_InsertReasonCodeProductTypeDescription_v1")]
		public int spDesktopDataAdmin_InsertReasonCodeProductTypeDescription_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCode", DbType="VarChar(3)")] string reasonCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCodeTypeId", DbType="Int")] System.Nullable<int> reasonCodeTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="NVarChar(5)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCodeProductTypeDescription", DbType="NVarChar(50)")] string reasonCodeProductTypeDescription, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reasonCode, productId, reasonCodeTypeId, languageCode, reasonCodeProductTypeDescription, adminUserGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectReasonCodeProductTypeDescriptionAvailableLanguages_v" +
			"1")]
		public ISingleResult<spDesktopDataAdmin_SelectReasonCodeProductTypeDescriptionAvailableLanguages_v1Result> spDesktopDataAdmin_SelectReasonCodeProductTypeDescriptionAvailableLanguages_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCode", DbType="VarChar(3)")] string reasonCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCodeTypeId", DbType="Int")] System.Nullable<int> reasonCodeTypeId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reasonCode, productId, reasonCodeTypeId);
			return ((ISingleResult<spDesktopDataAdmin_SelectReasonCodeProductTypeDescriptionAvailableLanguages_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectReasonCodeProductTypeDescriptions_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectReasonCodeProductTypeDescriptions_v1Result> spDesktopDataAdmin_SelectReasonCodeProductTypeDescriptions_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCode", DbType="VarChar(3)")] string reasonCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCodeTypeId", DbType="Int")] System.Nullable<int> reasonCodeTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortField", DbType="VarChar(50)")] string sortField, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reasonCode, productId, reasonCodeTypeId, sortField, sortOrder, pageNumber);
			return ((ISingleResult<spDesktopDataAdmin_SelectReasonCodeProductTypeDescriptions_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_UpdateReasonCodeProductTypeDescription_v1")]
		public int spDesktopDataAdmin_UpdateReasonCodeProductTypeDescription_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCode", DbType="VarChar(3)")] string reasonCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCodeTypeId", DbType="Int")] System.Nullable<int> reasonCodeTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="NVarChar(5)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonCodeProductTypeDescription", DbType="NVarChar(50)")] string reasonCodeProductTypeDescription, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reasonCode, productId, reasonCodeTypeId, languageCode, reasonCodeProductTypeDescription, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReasonCodeProductTypeDescription")]
	public partial class ReasonCodeProductTypeDescription : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ReasonCodeProductTypeDescription1;
		
		private string _LanguageCode;
		
		private string _ReasonCode;
		
		private int _ProductId;
		
		private int _ReasonCodeTypeId;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private int _VersionNumber;
		
		private string _ReasonCodeProductTypeExplanation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReasonCodeProductTypeDescription1Changing(string value);
    partial void OnReasonCodeProductTypeDescription1Changed();
    partial void OnLanguageCodeChanging(string value);
    partial void OnLanguageCodeChanged();
    partial void OnReasonCodeChanging(string value);
    partial void OnReasonCodeChanged();
    partial void OnProductIdChanging(int value);
    partial void OnProductIdChanged();
    partial void OnReasonCodeTypeIdChanging(int value);
    partial void OnReasonCodeTypeIdChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(int value);
    partial void OnVersionNumberChanged();
    partial void OnReasonCodeProductTypeExplanationChanging(string value);
    partial void OnReasonCodeProductTypeExplanationChanged();
    #endregion
		
		public ReasonCodeProductTypeDescription()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ReasonCodeProductTypeDescription", Storage="_ReasonCodeProductTypeDescription1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ReasonCodeProductTypeDescription1
		{
			get
			{
				return this._ReasonCodeProductTypeDescription1;
			}
			set
			{
				if ((this._ReasonCodeProductTypeDescription1 != value))
				{
					this.OnReasonCodeProductTypeDescription1Changing(value);
					this.SendPropertyChanging();
					this._ReasonCodeProductTypeDescription1 = value;
					this.SendPropertyChanged("ReasonCodeProductTypeDescription1");
					this.OnReasonCodeProductTypeDescription1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this.OnLanguageCodeChanging(value);
					this.SendPropertyChanging();
					this._LanguageCode = value;
					this.SendPropertyChanged("LanguageCode");
					this.OnLanguageCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonCode", DbType="VarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ReasonCode
		{
			get
			{
				return this._ReasonCode;
			}
			set
			{
				if ((this._ReasonCode != value))
				{
					this.OnReasonCodeChanging(value);
					this.SendPropertyChanging();
					this._ReasonCode = value;
					this.SendPropertyChanged("ReasonCode");
					this.OnReasonCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonCodeTypeId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ReasonCodeTypeId
		{
			get
			{
				return this._ReasonCodeTypeId;
			}
			set
			{
				if ((this._ReasonCodeTypeId != value))
				{
					this.OnReasonCodeTypeIdChanging(value);
					this.SendPropertyChanging();
					this._ReasonCodeTypeId = value;
					this.SendPropertyChanged("ReasonCodeTypeId");
					this.OnReasonCodeTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int NOT NULL")]
		public int VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonCodeProductTypeExplanation", DbType="NVarChar(1024)")]
		public string ReasonCodeProductTypeExplanation
		{
			get
			{
				return this._ReasonCodeProductTypeExplanation;
			}
			set
			{
				if ((this._ReasonCodeProductTypeExplanation != value))
				{
					this.OnReasonCodeProductTypeExplanationChanging(value);
					this.SendPropertyChanging();
					this._ReasonCodeProductTypeExplanation = value;
					this.SendPropertyChanged("ReasonCodeProductTypeExplanation");
					this.OnReasonCodeProductTypeExplanationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectReasonCodeProductTypeDescriptionAvailableLanguages_v1Result
	{
		
		private string _LanguageName;
		
		private string _LanguageCode;
		
		public spDesktopDataAdmin_SelectReasonCodeProductTypeDescriptionAvailableLanguages_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LanguageName
		{
			get
			{
				return this._LanguageName;
			}
			set
			{
				if ((this._LanguageName != value))
				{
					this._LanguageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this._LanguageCode = value;
				}
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectReasonCodeProductTypeDescriptions_v1Result
	{
		
		private string _LanguageCode;
		
		private string _LanguageName;
		
		private string _ReasonCodeProductTypeDescription;
		
		private System.Nullable<int> _RecordCount;
		
		public spDesktopDataAdmin_SelectReasonCodeProductTypeDescriptions_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this._LanguageCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LanguageName
		{
			get
			{
				return this._LanguageName;
			}
			set
			{
				if ((this._LanguageName != value))
				{
					this._LanguageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonCodeProductTypeDescription", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ReasonCodeProductTypeDescription
		{
			get
			{
				return this._ReasonCodeProductTypeDescription;
			}
			set
			{
				if ((this._ReasonCodeProductTypeDescription != value))
				{
					this._ReasonCodeProductTypeDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCount", DbType="Int")]
		public System.Nullable<int> RecordCount
		{
			get
			{
				return this._RecordCount;
			}
			set
			{
				if ((this._RecordCount != value))
				{
					this._RecordCount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
