<?xml version="1.0" encoding="utf-8"?><Database Name="Desktop_Local_v4021" Class="ServicingOptionItemDC" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.11.83;Initial Catalog=Desktop_Local_v4021;Persist Security Info=True;User ID=cdoadmin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Desktop_Local_v4021ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ServicingOptionItem" Member="ServicingOptionItems">
    <Type Name="ServicingOptionItem">
      <Column Name="ServicingOptionItemId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ServicingOptionGroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServicingOptionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServicingOptionItemValue" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ServicingOptionItemInstruction" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ServicingOptionItemSequence" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DisplayInApplicationFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GDSCode" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="LastUpdateTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdateUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ServicingOptionItem_ServicingOptionFareCalculation" Member="ServicingOptionFareCalculations" ThisKey="ServicingOptionItemId" OtherKey="ServicingOptionItemId" Type="ServicingOptionFareCalculation" />
    </Type>
  </Table>
  <Table Name="dbo.ServicingOptionFareCalculation" Member="ServicingOptionFareCalculations">
    <Type Name="ServicingOptionFareCalculation">
      <Column Name="ServicingOptionFareCalculationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ServicingOptionItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartureTimeWindowMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ArrivalTimeWindowMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaximumStops" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaximumConnectionTimeMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseAlternateAirportFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NoPenaltyFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NoRestrictionsFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreationTimeStamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="LastUpdateTimeStamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdateUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ServicingOptionItem_ServicingOptionFareCalculation" Member="ServicingOptionItem" ThisKey="ServicingOptionItemId" OtherKey="ServicingOptionItemId" Type="ServicingOptionItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.spDesktopDataAdmin_DeleteServicingOptionItem_v1" Method="spDesktopDataAdmin_DeleteServicingOptionItem_v1">
    <Parameter Name="ServicingOptionItemId" Parameter="servicingOptionItemId" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="VersionNumber" Parameter="versionNumber" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_UpdateServicingOptionItem_v1" Method="spDesktopDataAdmin_UpdateServicingOptionItem_v1">
    <Parameter Name="ServicingOptionItemId" Parameter="servicingOptionItemId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ServicingOptionId" Parameter="servicingOptionId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ServicingOptionItemValue" Parameter="servicingOptionItemValue" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="GDSCode" Parameter="gDSCode" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="ServicingOptionItemInstruction" Parameter="servicingOptionItemInstruction" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="DisplayInApplicationFlag" Parameter="displayInApplicationFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="DepartureTimeWindowMinutes" Parameter="departureTimeWindowMinutes" Type="System.Int32" DbType="Int" />
    <Parameter Name="ArrivalTimeWindowMinutes" Parameter="arrivalTimeWindowMinutes" Type="System.Int32" DbType="Int" />
    <Parameter Name="MaximumStops" Parameter="maximumStops" Type="System.Int32" DbType="Int" />
    <Parameter Name="MaximumConnectionTimeMinutes" Parameter="maximumConnectionTimeMinutes" Type="System.Int32" DbType="Int" />
    <Parameter Name="UseAlternateAirportFlag" Parameter="useAlternateAirportFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NoPenaltyFlag" Parameter="noPenaltyFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NoRestrictionsFlag" Parameter="noRestrictionsFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="VersionNumber" Parameter="versionNumber" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_SelectServicingOptionItems_v1" Method="spDesktopDataAdmin_SelectServicingOptionItems_v1">
    <Parameter Name="ServicingOptionGroupId" Parameter="servicingOptionGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SortField" Parameter="sortField" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SortOrder" Parameter="sortOrder" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageNumber" Parameter="pageNumber" Type="System.Int32" DbType="Int" />
    <ElementType Name="spDesktopDataAdmin_SelectServicingOptionItems_v1Result">
      <Column Name="ServicingOptionItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServicingOptionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServicingOptionItemValue" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ServicingOptionItemInstruction" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ServicingOptionItemSequence" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Parameters" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="DepartureTimeWindowMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ArrivalTimeWindowMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaximumStops" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaximumConnectionTimeMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseAlternateAirportFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NoPenaltyFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NoRestrictionsFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GDSName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ServicingOptionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RecordCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_InsertServicingOptionItem_v1" Method="spDesktopDataAdmin_InsertServicingOptionItem_v1">
    <Parameter Name="ServicingOptionGroupId" Parameter="servicingOptionGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ServicingOptionId" Parameter="servicingOptionId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ServicingOptionItemValue" Parameter="servicingOptionItemValue" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="GDSCode" Parameter="gDSCode" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="ServicingOptionItemInstruction" Parameter="servicingOptionItemInstruction" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="DisplayInApplicationFlag" Parameter="displayInApplicationFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="DepartureTimeWindowMinutes" Parameter="departureTimeWindowMinutes" Type="System.Int32" DbType="Int" />
    <Parameter Name="ArrivalTimeWindowMinutes" Parameter="arrivalTimeWindowMinutes" Type="System.Int32" DbType="Int" />
    <Parameter Name="MaximumStops" Parameter="maximumStops" Type="System.Int32" DbType="Int" />
    <Parameter Name="MaximumConnectionTimeMinutes" Parameter="maximumConnectionTimeMinutes" Type="System.Int32" DbType="Int" />
    <Parameter Name="UseAlternateAirportFlag" Parameter="useAlternateAirportFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NoPenaltyFlag" Parameter="noPenaltyFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NoRestrictionsFlag" Parameter="noRestrictionsFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Return Type="System.Int32" />
  </Function>
</Database>