<?xml version="1.0" encoding="utf-8"?><Database Name="Desktop_Local_v1841" Class="ServicingOptionGroupDC" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.11.90;Initial Catalog=Desktop_Local_v1841;Persist Security Info=True;User ID=cdoadmin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Desktop_Local_v1841" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ServicingOptionGroupLocation" Member="ServicingOptionGroupLocations">
    <Type Name="ServicingOptionGroupLocation">
      <Column Name="ServicingOptionGroupId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LocationId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="LastUpdateTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdateUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ServicingOptionGroup_ServicingOptionGroupLocation" Member="ServicingOptionGroup" ThisKey="ServicingOptionGroupId" OtherKey="ServicingOptionGroupId" Type="ServicingOptionGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ServicingOptionGroupTeam" Member="ServicingOptionGroupTeams">
    <Type Name="ServicingOptionGroupTeam">
      <Column Name="ServicingOptionGroupId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TeamId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="LastUpdateTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdateUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ServicingOptionGroup_ServicingOptionGroupTeam" Member="ServicingOptionGroup" ThisKey="ServicingOptionGroupId" OtherKey="ServicingOptionGroupId" Type="ServicingOptionGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ServicingOptionGroup" Member="ServicingOptionGroups">
    <Type Name="ServicingOptionGroup">
      <Column Name="ServicingOptionGroupId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ServicingOptionGroupName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EnabledFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EnabledDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TripTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletedFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="LastUpdateTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdateUserIdentifier" Type="System.String" DbType="NVarChar(170)" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeetingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ServicingOptionGroup_ServicingOptionGroupLocation" Member="ServicingOptionGroupLocations" ThisKey="ServicingOptionGroupId" OtherKey="ServicingOptionGroupId" Type="ServicingOptionGroupLocation" />
      <Association Name="ServicingOptionGroup_ServicingOptionGroupTeam" Member="ServicingOptionGroupTeams" ThisKey="ServicingOptionGroupId" OtherKey="ServicingOptionGroupId" Type="ServicingOptionGroupTeam" />
    </Type>
  </Table>
  <Function Name="dbo.spDesktopDataAdmin_UpdateServicingOptionGroupDeletedStatus_v1" Method="spDesktopDataAdmin_UpdateServicingOptionGroupDeletedStatus_v1">
    <Parameter Name="ServicingOptionGroupId" Parameter="servicingOptionGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Deleted" Parameter="deleted" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="VersionNumber" Parameter="versionNumber" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_SelectServicingOptionGroups_v1" Method="spDesktopDataAdmin_SelectServicingOptionGroups_v1">
    <Parameter Name="DeletedFlag" Parameter="deletedFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Filter" Parameter="filter" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="SortField" Parameter="sortField" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SortOrder" Parameter="sortOrder" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageNumber" Parameter="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <ElementType Name="spDesktopDataAdmin_SelectServicingOptionGroups_v1Result">
      <Column Name="ServicingOptionGroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServicingOptionGroupName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LinkedItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HierarchyType" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="HasWriteAccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RecordCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_UpdateServicingOptionGroupLinkedClientSubUnit_v1" Method="spDesktopDataAdmin_UpdateServicingOptionGroupLinkedClientSubUnit_v1">
    <Parameter Name="ServicingOptionGroupId" Parameter="servicingOptionGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClientSubUnitGuid" Parameter="clientSubUnitGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fnDesktopDataAdmin_SelectServicingOptionGroupHierarchy_v1" Method="fnDesktopDataAdmin_SelectServicingOptionGroupHierarchy_v1" IsComposable="true">
    <Parameter Name="ServicingOptionGroupId" Parameter="servicingOptionGroupId" Type="System.Int32" DbType="Int" />
    <ElementType Name="fnDesktopDataAdmin_SelectServicingOptionGroupHierarchy_v1Result">
      <Column Name="HierarchyCode" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="HierarchyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HierarchyType" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TravelerTypeGuid" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="TravelerTypeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SourceSystemCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_SelectServicingOptionGroupsOrphaned_v1" Method="spDesktopDataAdmin_SelectServicingOptionGroupsOrphaned_v1">
    <Parameter Name="Filter" Parameter="filter" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="SortField" Parameter="sortField" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SortOrder" Parameter="sortOrder" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageNumber" Parameter="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <ElementType Name="spDesktopDataAdmin_SelectServicingOptionGroupsOrphaned_v1Result">
      <Column Name="ServicingOptionGroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServicingOptionGroupName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeletedFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasWriteAccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RecordCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_InsertServicingOptionGroup_v1" Method="spDesktopDataAdmin_InsertServicingOptionGroup_v1">
    <Parameter Name="ServicingOptionGroupName" Parameter="servicingOptionGroupName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="EnabledFlag" Parameter="enabledFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EnabledDate" Parameter="enabledDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ExpiryDate" Parameter="expiryDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="TripTypeId" Parameter="tripTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="HierarchyType" Parameter="hierarchyType" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="HierarchyItemCode" Parameter="hierarchyItemCode" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="TravelerTypeGuid" Parameter="travelerTypeGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="ClientSubUnitGuid" Parameter="clientSubUnitGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="SourceSystemCode" Parameter="sourceSystemCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="MeetingID" Parameter="meetingID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_UpdateServicingOptionGroup_v1" Method="spDesktopDataAdmin_UpdateServicingOptionGroup_v1">
    <Parameter Name="SystemUserGuid" Parameter="systemUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="ServicingOptionGroupId" Parameter="servicingOptionGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ServicingOptionGroupName" Parameter="servicingOptionGroupName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="EnabledFlag" Parameter="enabledFlag" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EnabledDate" Parameter="enabledDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ExpiryDate" Parameter="expiryDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="TripTypeId" Parameter="tripTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Hierarchy" Parameter="hierarchy" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="HierarchyItemCode" Parameter="hierarchyItemCode" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="TravelerTypeGuid" Parameter="travelerTypeGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="ClientSubUnitGuid" Parameter="clientSubUnitGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="SourceSystemCode" Parameter="sourceSystemCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="IsMultipleHierarchy" Parameter="isMultipleHierarchy" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="MeetingID" Parameter="meetingID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="VersionNumber" Parameter="versionNumber" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDesktopDataAdmin_SelectServicingOptionGroupLinkedClientSubUnits_v1" Method="spDesktopDataAdmin_SelectServicingOptionGroupLinkedClientSubUnits_v1">
    <Parameter Name="ServicingOptionGroupId" Parameter="servicingOptionGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminUserGuid" Parameter="adminUserGuid" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="Linked" Parameter="linked" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="spDesktopDataAdmin_SelectServicingOptionGroupLinkedClientSubUnits_v1Result">
      <Column Name="ClientSubUnitGuid" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="ClientSubUnitName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HasWriteAccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsClientExpiredFlag" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>