#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Desktop_Local_v4021")]
	public partial class ServicingOptionDC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertServicingOption(ServicingOption instance);
    partial void UpdateServicingOption(ServicingOption instance);
    partial void DeleteServicingOption(ServicingOption instance);
    #endregion
		
		public ServicingOptionDC() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Desktop_Local_v4021ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ServicingOptionDC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ServicingOptionDC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ServicingOptionDC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ServicingOptionDC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ServicingOption> ServicingOptions
		{
			get
			{
				return this.GetTable<ServicingOption>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ServicingOption")]
	public partial class ServicingOption : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ServicingOptionId;
		
		private string _ServicingOptionName;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private int _VersionNumber;
		
		private bool _GDSRequiredFlag;
		
		private bool _AllowEditOrderFlag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnServicingOptionIdChanging(int value);
    partial void OnServicingOptionIdChanged();
    partial void OnServicingOptionNameChanging(string value);
    partial void OnServicingOptionNameChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(int value);
    partial void OnVersionNumberChanged();
    partial void OnGDSRequiredFlagChanging(bool value);
    partial void OnGDSRequiredFlagChanged();
    partial void OnAllowEditOrderFlagChanging(bool value);
    partial void OnAllowEditOrderFlagChanged();
    #endregion
		
		public ServicingOption()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServicingOptionId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ServicingOptionId
		{
			get
			{
				return this._ServicingOptionId;
			}
			set
			{
				if ((this._ServicingOptionId != value))
				{
					this.OnServicingOptionIdChanging(value);
					this.SendPropertyChanging();
					this._ServicingOptionId = value;
					this.SendPropertyChanged("ServicingOptionId");
					this.OnServicingOptionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServicingOptionName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ServicingOptionName
		{
			get
			{
				return this._ServicingOptionName;
			}
			set
			{
				if ((this._ServicingOptionName != value))
				{
					this.OnServicingOptionNameChanging(value);
					this.SendPropertyChanging();
					this._ServicingOptionName = value;
					this.SendPropertyChanged("ServicingOptionName");
					this.OnServicingOptionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int NOT NULL")]
		public int VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GDSRequiredFlag", DbType="Bit NOT NULL")]
		public bool GDSRequiredFlag
		{
			get
			{
				return this._GDSRequiredFlag;
			}
			set
			{
				if ((this._GDSRequiredFlag != value))
				{
					this.OnGDSRequiredFlagChanging(value);
					this.SendPropertyChanging();
					this._GDSRequiredFlag = value;
					this.SendPropertyChanged("GDSRequiredFlag");
					this.OnGDSRequiredFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowEditOrderFlag", DbType="Bit NOT NULL")]
		public bool AllowEditOrderFlag
		{
			get
			{
				return this._AllowEditOrderFlag;
			}
			set
			{
				if ((this._AllowEditOrderFlag != value))
				{
					this.OnAllowEditOrderFlagChanging(value);
					this.SendPropertyChanging();
					this._AllowEditOrderFlag = value;
					this.SendPropertyChanged("AllowEditOrderFlag");
					this.OnAllowEditOrderFlagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
