#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ClientDesktopPreProduction")]
	public partial class SystemUserLocationDC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSystemUserLocation(SystemUserLocation instance);
    partial void UpdateSystemUserLocation(SystemUserLocation instance);
    partial void DeleteSystemUserLocation(SystemUserLocation instance);
    #endregion
		
		public SystemUserLocationDC() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CWTDesktopDatabase"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SystemUserLocationDC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SystemUserLocationDC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SystemUserLocationDC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SystemUserLocationDC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SystemUserLocation> SystemUserLocations
		{
			get
			{
				return this.GetTable<SystemUserLocation>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_InsertSystemUserLocation_v1")]
		public int spDesktopDataAdmin_InsertSystemUserLocation_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SystemUserGuid", DbType="VarChar(13)")] string systemUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LocationId", DbType="Int")] System.Nullable<int> locationId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), systemUserGuid, locationId, adminUserGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_UpdateSystemUserLocation_v1")]
		public int spDesktopDataAdmin_UpdateSystemUserLocation_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SystemUserGuid", DbType="VarChar(13)")] string systemUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LocationId", DbType="Int")] System.Nullable<int> locationId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), systemUserGuid, locationId, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SystemUserLocation")]
	public partial class SystemUserLocation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SystemUserGuid;
		
		private int _LocationId;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private System.Nullable<int> _VersionNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSystemUserGuidChanging(string value);
    partial void OnSystemUserGuidChanged();
    partial void OnLocationIdChanging(int value);
    partial void OnLocationIdChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(System.Nullable<int> value);
    partial void OnVersionNumberChanged();
    #endregion
		
		public SystemUserLocation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemUserGuid", DbType="VarChar(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SystemUserGuid
		{
			get
			{
				return this._SystemUserGuid;
			}
			set
			{
				if ((this._SystemUserGuid != value))
				{
					this.OnSystemUserGuidChanging(value);
					this.SendPropertyChanging();
					this._SystemUserGuid = value;
					this.SendPropertyChanged("SystemUserGuid");
					this.OnSystemUserGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationId", DbType="Int NOT NULL")]
		public int LocationId
		{
			get
			{
				return this._LocationId;
			}
			set
			{
				if ((this._LocationId != value))
				{
					this.OnLocationIdChanging(value);
					this.SendPropertyChanging();
					this._LocationId = value;
					this.SendPropertyChanged("LocationId");
					this.OnLocationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int")]
		public System.Nullable<int> VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
