#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDesktopDatabase.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Desktop_Local_v1841")]
	public partial class TripTypeItemDC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTripTypeItem(TripTypeItem instance);
    partial void UpdateTripTypeItem(TripTypeItem instance);
    partial void DeleteTripTypeItem(TripTypeItem instance);
    #endregion
		
		public TripTypeItemDC() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Desktop_Local_v1841"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TripTypeItemDC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TripTypeItemDC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TripTypeItemDC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TripTypeItemDC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TripTypeItem> TripTypeItems
		{
			get
			{
				return this.GetTable<TripTypeItem>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectTripTypeGroupAvailableTripTypeItems_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectTripTypeGroupAvailableTripTypeItems_v1Result> spDesktopDataAdmin_SelectTripTypeGroupAvailableTripTypeItems_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripTypeGroupId", DbType="Int")] System.Nullable<int> tripTypeGroupId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tripTypeGroupId);
			return ((ISingleResult<spDesktopDataAdmin_SelectTripTypeGroupAvailableTripTypeItems_v1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_InsertTripTypeItem_v1")]
		public int spDesktopDataAdmin_InsertTripTypeItem_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripTypeGroupId", DbType="Int")] System.Nullable<int> tripTypeGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripTypeId", DbType="Int")] System.Nullable<int> tripTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DefaultTripTypeFlag", DbType="Bit")] System.Nullable<bool> defaultTripTypeFlag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tripTypeGroupId, tripTypeId, defaultTripTypeFlag, adminUserGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_UpdateTripTypeItem_v1")]
		public int spDesktopDataAdmin_UpdateTripTypeItem_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripTypeGroupId", DbType="Int")] System.Nullable<int> tripTypeGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripTypeId", DbType="Int")] System.Nullable<int> tripTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DefaultTripTypeFlag", DbType="Bit")] System.Nullable<bool> defaultTripTypeFlag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tripTypeGroupId, tripTypeId, defaultTripTypeFlag, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_DeleteTripTypeItem_v1")]
		public int spDesktopDataAdmin_DeleteTripTypeItem_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripTypeGroupId", DbType="Int")] System.Nullable<int> tripTypeGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripTypeId", DbType="Int")] System.Nullable<int> tripTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminUserGuid", DbType="VarChar(13)")] string adminUserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionNumber", DbType="Int")] System.Nullable<int> versionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tripTypeGroupId, tripTypeId, adminUserGuid, versionNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDesktopDataAdmin_SelectTripTypeItems_v1")]
		public ISingleResult<spDesktopDataAdmin_SelectTripTypeItems_v1Result> spDesktopDataAdmin_SelectTripTypeItems_v1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripTypeGroupId", DbType="Int")] System.Nullable<int> tripTypeGroupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filter", DbType="VarChar(50)")] string filter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortField", DbType="VarChar(50)")] string sortField, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNumber", DbType="Int")] System.Nullable<int> pageNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tripTypeGroupId, filter, sortField, sortOrder, pageNumber);
			return ((ISingleResult<spDesktopDataAdmin_SelectTripTypeItems_v1Result>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TripTypeItem")]
	public partial class TripTypeItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TripTypeGroupId;
		
		private int _TripTypeId;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private string _CreationUserIdentifier;
		
		private System.Nullable<System.DateTime> _LastUpdateTimestamp;
		
		private string _LastUpdateUserIdentifier;
		
		private System.Nullable<int> _VersionNumber;
		
		private System.Nullable<bool> _DefaultTripTypeFlag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTripTypeGroupIdChanging(int value);
    partial void OnTripTypeGroupIdChanged();
    partial void OnTripTypeIdChanging(int value);
    partial void OnTripTypeIdChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnCreationUserIdentifierChanging(string value);
    partial void OnCreationUserIdentifierChanged();
    partial void OnLastUpdateTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateTimestampChanged();
    partial void OnLastUpdateUserIdentifierChanging(string value);
    partial void OnLastUpdateUserIdentifierChanged();
    partial void OnVersionNumberChanging(System.Nullable<int> value);
    partial void OnVersionNumberChanged();
    partial void OnDefaultTripTypeFlagChanging(System.Nullable<bool> value);
    partial void OnDefaultTripTypeFlagChanged();
    #endregion
		
		public TripTypeItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripTypeGroupId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TripTypeGroupId
		{
			get
			{
				return this._TripTypeGroupId;
			}
			set
			{
				if ((this._TripTypeGroupId != value))
				{
					this.OnTripTypeGroupIdChanging(value);
					this.SendPropertyChanging();
					this._TripTypeGroupId = value;
					this.SendPropertyChanged("TripTypeGroupId");
					this.OnTripTypeGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripTypeId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TripTypeId
		{
			get
			{
				return this._TripTypeId;
			}
			set
			{
				if ((this._TripTypeId != value))
				{
					this.OnTripTypeIdChanging(value);
					this.SendPropertyChanging();
					this._TripTypeId = value;
					this.SendPropertyChanged("TripTypeId");
					this.OnTripTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationUserIdentifier", DbType="NVarChar(170)")]
		public string CreationUserIdentifier
		{
			get
			{
				return this._CreationUserIdentifier;
			}
			set
			{
				if ((this._CreationUserIdentifier != value))
				{
					this.OnCreationUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._CreationUserIdentifier = value;
					this.SendPropertyChanged("CreationUserIdentifier");
					this.OnCreationUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdateTimestamp
		{
			get
			{
				return this._LastUpdateTimestamp;
			}
			set
			{
				if ((this._LastUpdateTimestamp != value))
				{
					this.OnLastUpdateTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateTimestamp = value;
					this.SendPropertyChanged("LastUpdateTimestamp");
					this.OnLastUpdateTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdateUserIdentifier", DbType="NVarChar(170)")]
		public string LastUpdateUserIdentifier
		{
			get
			{
				return this._LastUpdateUserIdentifier;
			}
			set
			{
				if ((this._LastUpdateUserIdentifier != value))
				{
					this.OnLastUpdateUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._LastUpdateUserIdentifier = value;
					this.SendPropertyChanged("LastUpdateUserIdentifier");
					this.OnLastUpdateUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="Int")]
		public System.Nullable<int> VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultTripTypeFlag", DbType="Bit")]
		public System.Nullable<bool> DefaultTripTypeFlag
		{
			get
			{
				return this._DefaultTripTypeFlag;
			}
			set
			{
				if ((this._DefaultTripTypeFlag != value))
				{
					this.OnDefaultTripTypeFlagChanging(value);
					this.SendPropertyChanging();
					this._DefaultTripTypeFlag = value;
					this.SendPropertyChanged("DefaultTripTypeFlag");
					this.OnDefaultTripTypeFlagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectTripTypeGroupAvailableTripTypeItems_v1Result
	{
		
		private int _TripTypeId;
		
		private string _TripTypeDescription;
		
		public spDesktopDataAdmin_SelectTripTypeGroupAvailableTripTypeItems_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripTypeId", DbType="Int NOT NULL")]
		public int TripTypeId
		{
			get
			{
				return this._TripTypeId;
			}
			set
			{
				if ((this._TripTypeId != value))
				{
					this._TripTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripTypeDescription", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TripTypeDescription
		{
			get
			{
				return this._TripTypeDescription;
			}
			set
			{
				if ((this._TripTypeDescription != value))
				{
					this._TripTypeDescription = value;
				}
			}
		}
	}
	
	public partial class spDesktopDataAdmin_SelectTripTypeItems_v1Result
	{
		
		private int _TripTypeId;
		
		private string _TripTypeDescription;
		
		private string _BackOfficeTripTypeCode;
		
		private System.Nullable<bool> _DefaultTripTypeFlag;
		
		private System.Nullable<int> _RecordCount;
		
		public spDesktopDataAdmin_SelectTripTypeItems_v1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripTypeId", DbType="Int NOT NULL")]
		public int TripTypeId
		{
			get
			{
				return this._TripTypeId;
			}
			set
			{
				if ((this._TripTypeId != value))
				{
					this._TripTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripTypeDescription", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TripTypeDescription
		{
			get
			{
				return this._TripTypeDescription;
			}
			set
			{
				if ((this._TripTypeDescription != value))
				{
					this._TripTypeDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackOfficeTripTypeCode", DbType="NVarChar(10)")]
		public string BackOfficeTripTypeCode
		{
			get
			{
				return this._BackOfficeTripTypeCode;
			}
			set
			{
				if ((this._BackOfficeTripTypeCode != value))
				{
					this._BackOfficeTripTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultTripTypeFlag", DbType="Bit")]
		public System.Nullable<bool> DefaultTripTypeFlag
		{
			get
			{
				return this._DefaultTripTypeFlag;
			}
			set
			{
				if ((this._DefaultTripTypeFlag != value))
				{
					this._DefaultTripTypeFlag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCount", DbType="Int")]
		public System.Nullable<int> RecordCount
		{
			get
			{
				return this._RecordCount;
			}
			set
			{
				if ((this._RecordCount != value))
				{
					this._RecordCount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
